//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.MapGuide.Maestro.ResourceValidators.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebLayoutValidator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebLayoutValidator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.MapGuide.Maestro.ResourceValidators.Strings.WebLayoutValidator", typeof(WebLayoutValidator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one viewer command named: {0}.
        /// </summary>
        internal static string DuplicateCommandName {
            get {
                return ResourceManager.GetString("DuplicateCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search command {0} has a duplicate result property {1}.
        /// </summary>
        internal static string DuplicateSearchResultColumn {
            get {
                return ResourceManager.GetString("DuplicateSearchResultColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating MapDefinition {0}, message: {1}.
        /// </summary>
        internal static string MapValidationError {
            get {
                return ResourceManager.GetString("MapValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout does not specify a map.
        /// </summary>
        internal static string MissingMapError {
            get {
                return ResourceManager.GetString("MissingMapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu contains a reference to a command that doesn&apos;t exist: {0}.
        /// </summary>
        internal static string NonExistentMenuCommandReference {
            get {
                return ResourceManager.GetString("NonExistentMenuCommandReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Pane contains a reference to a command that does not exist: {0}.
        /// </summary>
        internal static string NonExistentTaskPaneCommandReference {
            get {
                return ResourceManager.GetString("NonExistentTaskPaneCommandReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar contains a reference to a command that does not exist: {0}.
        /// </summary>
        internal static string NonExistentToolbarCommandReference {
            get {
                return ResourceManager.GetString("NonExistentToolbarCommandReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout specifies a start view that is outside the map&apos;s initial extents.
        /// </summary>
        internal static string StartViewOutsideExtentsWarning {
            get {
                return ResourceManager.GetString("StartViewOutsideExtentsWarning", resourceCulture);
            }
        }
    }
}
