//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maestro.MapViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maestro.MapViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap buffer {
            get {
                object obj = ResourceManager.GetObject("buffer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to finish.
        /// </summary>
        internal static string CircleDigitizationPrompt {
            get {
                return ResourceManager.GetString("CircleDigitizationPrompt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap control {
            get {
                object obj = ResourceManager.GetObject("control", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_180 {
            get {
                object obj = ResourceManager.GetObject("control_180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} features in layer.
        /// </summary>
        internal static string CountFormat {
            get {
                return ResourceManager.GetString("CountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {1}{0}Feature Source: {2}{0}Feature Class: {3}.
        /// </summary>
        internal static string DefaultLayerTooltip {
            get {
                return ResourceManager.GetString("DefaultLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {1}{0}Feature Source: {2}.
        /// </summary>
        internal static string DrawingLayerTooltip {
            get {
                return ResourceManager.GetString("DrawingLayerTooltip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap edit_copy {
            get {
                object obj = ResourceManager.GetObject("edit_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_cut {
            get {
                object obj = ResourceManager.GetObject("edit_cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_duplicate {
            get {
                object obj = ResourceManager.GetObject("edit_duplicate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_paste {
            get {
                object obj = ResourceManager.GetObject("edit_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap edit_xml {
            get {
                object obj = ResourceManager.GetObject("edit_xml", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_print {
            get {
                object obj = ResourceManager.GetObject("file_print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file_save {
            get {
                object obj = ResourceManager.GetObject("file_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to cancel.
        /// </summary>
        internal static string GeneralDigitizationInstructions {
            get {
                return ResourceManager.GetString("GeneralDigitizationInstructions", resourceCulture);
            }
        }
        
        internal static byte[] grab {
            get {
                object obj = ResourceManager.GetObject("grab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_etc {
            get {
                object obj = ResourceManager.GetObject("icon_etc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_home {
            get {
                object obj = ResourceManager.GetObject("icon_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_loading {
            get {
                object obj = ResourceManager.GetObject("icon_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_pan {
            get {
                object obj = ResourceManager.GetObject("icon_pan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_select {
            get {
                object obj = ResourceManager.GetObject("icon_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_tasks {
            get {
                object obj = ResourceManager.GetObject("icon_tasks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_zoomselect {
            get {
                object obj = ResourceManager.GetObject("icon_zoomselect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap iconNavigator {
            get {
                object obj = ResourceManager.GetObject("iconNavigator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap initial_center {
            get {
                object obj = ResourceManager.GetObject("initial_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoke_script {
            get {
                object obj = ResourceManager.GetObject("invoke_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoke_url {
            get {
                object obj = ResourceManager.GetObject("invoke_url", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_shape {
            get {
                object obj = ResourceManager.GetObject("layer_shape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_shape_ellipse {
            get {
                object obj = ResourceManager.GetObject("layer_shape_ellipse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_shape_line {
            get {
                object obj = ResourceManager.GetObject("layer_shape_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_shape_polygon {
            get {
                object obj = ResourceManager.GetObject("layer_shape_polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_shape_polyline {
            get {
                object obj = ResourceManager.GetObject("layer_shape_polyline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layer_small {
            get {
                object obj = ResourceManager.GetObject("layer_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_broken {
            get {
                object obj = ResourceManager.GetObject("lc_broken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_dwf {
            get {
                object obj = ResourceManager.GetObject("lc_dwf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_group {
            get {
                object obj = ResourceManager.GetObject("lc_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_raster {
            get {
                object obj = ResourceManager.GetObject("lc_raster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_select {
            get {
                object obj = ResourceManager.GetObject("lc_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_theme {
            get {
                object obj = ResourceManager.GetObject("lc_theme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lc_unselect {
            get {
                object obj = ResourceManager.GetObject("lc_unselect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to finish.
        /// </summary>
        internal static string LineDigitizationPrompt {
            get {
                return ResourceManager.GetString("LineDigitizationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click again to add a new vertex.\nDouble-click to finish.
        /// </summary>
        internal static string LineStringDigitizationPrompt {
            get {
                return ResourceManager.GetString("LineStringDigitizationPrompt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap load_package {
            get {
                object obj = ResourceManager.GetObject("load_package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap measure {
            get {
                object obj = ResourceManager.GetObject("measure", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap monitor_status {
            get {
                object obj = ResourceManager.GetObject("monitor_status", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl-Z to undo last point.\nPress ESC to cancel.
        /// </summary>
        internal static string MultiSegmentDigitzationInstructions {
            get {
                return ResourceManager.GetString("MultiSegmentDigitzationInstructions", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap options {
            get {
                object obj = ResourceManager.GetObject("options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap overview_map {
            get {
                object obj = ResourceManager.GetObject("overview_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to finish.
        /// </summary>
        internal static string PointDigitizationPrompt {
            get {
                return ResourceManager.GetString("PointDigitizationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click again to add a new vertex.\nDouble-click to finish.
        /// </summary>
        internal static string PolygonDigitizationPrompt {
            get {
                return ResourceManager.GetString("PolygonDigitizationPrompt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PoweredBy_en {
            get {
                object obj = ResourceManager.GetObject("PoweredBy_en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preview {
            get {
                object obj = ResourceManager.GetObject("preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to finish.
        /// </summary>
        internal static string RectangleDigitizationPrompt {
            get {
                return ResourceManager.GetString("RectangleDigitizationPrompt", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_centre {
            get {
                object obj = ResourceManager.GetObject("select_centre", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_clear {
            get {
                object obj = ResourceManager.GetObject("select_clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_features {
            get {
                object obj = ResourceManager.GetObject("select_features", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_polygon {
            get {
                object obj = ResourceManager.GetObject("select_polygon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_radius {
            get {
                object obj = ResourceManager.GetObject("select_radius", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_zoom {
            get {
                object obj = ResourceManager.GetObject("select_zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Selection.
        /// </summary>
        internal static string TextClearSelection {
            get {
                return ResourceManager.GetString("TextClearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: {0:0.0000000}, Y: {1:0.0000000}.
        /// </summary>
        internal static string TextCoordinatePosition {
            get {
                return ResourceManager.GetString("TextCoordinatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy map to clipboard.
        /// </summary>
        internal static string TextCopyMap {
            get {
                return ResourceManager.GetString("TextCopyMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Circle.
        /// </summary>
        internal static string TextDigitizeCircle {
            get {
                return ResourceManager.GetString("TextDigitizeCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Line.
        /// </summary>
        internal static string TextDigitizeLine {
            get {
                return ResourceManager.GetString("TextDigitizeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Line String.
        /// </summary>
        internal static string TextDigitizeLineString {
            get {
                return ResourceManager.GetString("TextDigitizeLineString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Point.
        /// </summary>
        internal static string TextDigitizePoint {
            get {
                return ResourceManager.GetString("TextDigitizePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Polygon.
        /// </summary>
        internal static string TextDigitizePolygon {
            get {
                return ResourceManager.GetString("TextDigitizePolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitize Rectangle.
        /// </summary>
        internal static string TextDigitizeRectangle {
            get {
                return ResourceManager.GetString("TextDigitizeRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Tooltips.
        /// </summary>
        internal static string TextDisableTooltips {
            get {
                return ResourceManager.GetString("TextDisableTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Tooltips.
        /// </summary>
        internal static string TextEnableTooltips {
            get {
                return ResourceManager.GetString("TextEnableTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TextExitApplication {
            get {
                return ResourceManager.GetString("TextExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Package.
        /// </summary>
        internal static string TextLoadPackage {
            get {
                return ResourceManager.GetString("TextLoadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing is selected.
        /// </summary>
        internal static string TextNoSelection {
            get {
                return ResourceManager.GetString("TextNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Saved.
        /// </summary>
        internal static string TextOptionsSaved {
            get {
                return ResourceManager.GetString("TextOptionsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Loaded.
        /// </summary>
        internal static string TextPackageLoaded {
            get {
                return ResourceManager.GetString("TextPackageLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan.
        /// </summary>
        internal static string TextPan {
            get {
                return ResourceManager.GetString("TextPan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot to DWF.
        /// </summary>
        internal static string TextPlotToDwf {
            get {
                return ResourceManager.GetString("TextPlotToDwf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string TextPrint {
            get {
                return ResourceManager.GetString("TextPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Map.
        /// </summary>
        internal static string TextRefreshMap {
            get {
                return ResourceManager.GetString("TextRefreshMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        internal static string TextScale {
            get {
                return ResourceManager.GetString("TextScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string TextSelect {
            get {
                return ResourceManager.GetString("TextSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} features selected.
        /// </summary>
        internal static string TextSelectedFeatures {
            get {
                return ResourceManager.GetString("TextSelectedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Polygon.
        /// </summary>
        internal static string TextSelectPolygon {
            get {
                return ResourceManager.GetString("TextSelectPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Radius.
        /// </summary>
        internal static string TextSelectRadius {
            get {
                return ResourceManager.GetString("TextSelectRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Pane.
        /// </summary>
        internal static string TextTaskPane {
            get {
                return ResourceManager.GetString("TextTaskPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer Options.
        /// </summary>
        internal static string TextViewerOptions {
            get {
                return ResourceManager.GetString("TextViewerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Extents.
        /// </summary>
        internal static string TextZoomExtents {
            get {
                return ResourceManager.GetString("TextZoomExtents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string TextZoomIn {
            get {
                return ResourceManager.GetString("TextZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Next.
        /// </summary>
        internal static string TextZoomNext {
            get {
                return ResourceManager.GetString("TextZoomNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string TextZoomOut {
            get {
                return ResourceManager.GetString("TextZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Previous.
        /// </summary>
        internal static string TextZoomPrevious {
            get {
                return ResourceManager.GetString("TextZoomPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to Selection.
        /// </summary>
        internal static string TextZoomToSelection {
            get {
                return ResourceManager.GetString("TextZoomToSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {1}{0}Feature Source: {2}{0}Feature Class: {3}{0}Number of Rules: {4}.
        /// </summary>
        internal static string ThemedLayerTooltip {
            get {
                return ResourceManager.GetString("ThemedLayerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer.
        /// </summary>
        internal static string TitleBuffer {
            get {
                return ResourceManager.GetString("TitleBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        internal static string TitleMeasure {
            get {
                return ResourceManager.GetString("TitleMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Settings.
        /// </summary>
        internal static string TitlePrintSettings {
            get {
                return ResourceManager.GetString("TitlePrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string TitleQuery {
            get {
                return ResourceManager.GetString("TitleQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string TitleTheme {
            get {
                return ResourceManager.GetString("TitleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer Options.
        /// </summary>
        internal static string TitleViewerOptions {
            get {
                return ResourceManager.GetString("TitleViewerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips are enabled. Click to disable.
        /// </summary>
        internal static string TooltipDisableTooltips {
            get {
                return ResourceManager.GetString("TooltipDisableTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltips are disabled. Click to enable.
        /// </summary>
        internal static string TooltipEnableTooltips {
            get {
                return ResourceManager.GetString("TooltipEnableTooltips", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ui_tooltip_balloon_bottom {
            get {
                object obj = ResourceManager.GetObject("ui_tooltip_balloon_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_back {
            get {
                object obj = ResourceManager.GetObject("view_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_forward {
            get {
                object obj = ResourceManager.GetObject("view_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_log {
            get {
                object obj = ResourceManager.GetObject("view_log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_refresh {
            get {
                object obj = ResourceManager.GetObject("view_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_dynamic {
            get {
                object obj = ResourceManager.GetObject("zoom_dynamic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_full {
            get {
                object obj = ResourceManager.GetObject("zoom_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_in_fixed {
            get {
                object obj = ResourceManager.GetObject("zoom_in_fixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap zoom_out_fixed {
            get {
                object obj = ResourceManager.GetObject("zoom_out_fixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] zoomin {
            get {
                object obj = ResourceManager.GetObject("zoomin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] zoomout {
            get {
                object obj = ResourceManager.GetObject("zoomout", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
