//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maestro.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maestro.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected language: {0}, OS Language: {1}.
        /// </summary>
        internal static string About_LanguageLabel {
            get {
                return ResourceManager.GetString("About_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapGuide Version: {0} ({1}).
        /// </summary>
        internal static string About_ServerVersionLabel {
            get {
                return ResourceManager.GetString("About_ServerVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string About_VersionLabel {
            get {
                return ResourceManager.GetString("About_VersionLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap application_browser {
            get {
                object obj = ResourceManager.GetObject("application_browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_sidebar_list {
            get {
                object obj = ResourceManager.GetObject("application_sidebar_list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap application_task {
            get {
                object obj = ResourceManager.GetObject("application_task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap applications_stack {
            get {
                object obj = ResourceManager.GetObject("applications_stack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow {
            get {
                object obj = ResourceManager.GetObject("arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_180 {
            get {
                object obj = ResourceManager.GetObject("arrow-180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_circle_045_left {
            get {
                object obj = ResourceManager.GetObject("arrow-circle-045-left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blueprints {
            get {
                object obj = ResourceManager.GetObject("blueprints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decode the current bounds,
        ///you may enter new bounds, and these will replace the current.
        ///Error message: {0}.
        /// </summary>
        internal static string BoundsPicker_BoundsDecodeError {
            get {
                return ResourceManager.GetString("BoundsPicker_BoundsDecodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered all the required information..
        /// </summary>
        internal static string BoundsPicker_IncompleBoundsError {
            get {
                return ResourceManager.GetString("BoundsPicker_IncompleBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert the Max X value.
        /// </summary>
        internal static string BoundsPicker_InvalidMaxXError {
            get {
                return ResourceManager.GetString("BoundsPicker_InvalidMaxXError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert the Max Y value.
        /// </summary>
        internal static string BoundsPicker_InvalidMaxYError {
            get {
                return ResourceManager.GetString("BoundsPicker_InvalidMaxYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert the Min X value.
        /// </summary>
        internal static string BoundsPicker_InvalidMinXError {
            get {
                return ResourceManager.GetString("BoundsPicker_InvalidMinXError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert the Min Y value.
        /// </summary>
        internal static string BoundsPicker_InvalidMinYError {
            get {
                return ResourceManager.GetString("BoundsPicker_InvalidMinYError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing bounds tag.
        /// </summary>
        internal static string BoundsPicker_MissingBoundsError {
            get {
                return ResourceManager.GetString("BoundsPicker_MissingBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values you have entered appears to be in local regional format, but are required in US regional format.
        ///Do you want to convert the values?.
        /// </summary>
        internal static string BoundsPicker_NumbersInRegionalError {
            get {
                return ResourceManager.GetString("BoundsPicker_NumbersInRegionalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The coordinates you have entered appears to be invalid, do you want to use them anyway?.
        /// </summary>
        internal static string BoundsPicker_UseInvalidCoordinatesWarning {
            get {
                return ResourceManager.GetString("BoundsPicker_UseInvalidCoordinatesWarning", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap box__arrow {
            get {
                object obj = ResourceManager.GetObject("box__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box__plus {
            get {
                object obj = ResourceManager.GetObject("box__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Browser_Complete {
            get {
                return ResourceManager.GetString("Browser_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Browser_Loading {
            get {
                return ResourceManager.GetString("Browser_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Feature Source Cache.
        /// </summary>
        internal static string CacheView {
            get {
                return ResourceManager.GetString("CacheView", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap clipboard_paste {
            get {
                object obj = ResourceManager.GetObject("clipboard_paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item {1} into {2}.
        /// </summary>
        internal static string ClipboardAction {
            get {
                return ResourceManager.GetString("ClipboardAction", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource {0} has unsaved changes. Close and discard these changes?.
        /// </summary>
        internal static string CloseUnsavedResource {
            get {
                return ResourceManager.GetString("CloseUnsavedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This map definition has tiled layers. Saving this map definition will reset the tile cache if these layer existed when you first edited this map. Continue with save?.
        /// </summary>
        internal static string ConfirmBaseMapInvalidation {
            get {
                return ResourceManager.GetString("ConfirmBaseMapInvalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature source is refrenced by at least one tiled layer in the following maps: {0} Saving this feature source may reset the cached tiles of these maps. Continue with save?.
        /// </summary>
        internal static string ConfirmBaseMapInvalidationFeatureSourceSave {
            get {
                return ResourceManager.GetString("ConfirmBaseMapInvalidationFeatureSourceSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This layer is used as a tiled layer in the following maps: {0} Saving this layer may reset the cached tiles of these maps. Continue with save?.
        /// </summary>
        internal static string ConfirmBaseMapInvalidationLayerSave {
            get {
                return ResourceManager.GetString("ConfirmBaseMapInvalidationLayerSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have open editors with unsaved changes. Continue anyway?.
        /// </summary>
        internal static string ConfirmCloseEditors {
            get {
                return ResourceManager.GetString("ConfirmCloseEditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete one or more resources which are currently open in an editor. Close these editors and proceed with delete?.
        /// </summary>
        internal static string ConfirmDeleteOpenResource {
            get {
                return ResourceManager.GetString("ConfirmDeleteOpenResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to load this package file?.
        /// </summary>
        internal static string ConfirmLoadPackage {
            get {
                return ResourceManager.GetString("ConfirmLoadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to move the following resources?.
        /// </summary>
        internal static string ConfirmMove {
            get {
                return ResourceManager.GetString("ConfirmMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to reset all preferences to default values. Are you sure you want to do this?.
        /// </summary>
        internal static string ConfirmResetPrefs {
            get {
                return ResourceManager.GetString("ConfirmResetPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        internal static string Content_Messages {
            get {
                return ResourceManager.GetString("Content_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbound Requests.
        /// </summary>
        internal static string Content_OutboundRequests {
            get {
                return ResourceManager.GetString("Content_OutboundRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Explorer.
        /// </summary>
        internal static string Content_SiteExplorer {
            get {
                return ResourceManager.GetString("Content_SiteExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded Web Browser.
        /// </summary>
        internal static string Content_WebBrowser {
            get {
                return ResourceManager.GetString("Content_WebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        internal static string Content_Welcome {
            get {
                return ResourceManager.GetString("Content_Welcome", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cross {
            get {
                object obj = ResourceManager.GetObject("cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross_circle {
            get {
                object obj = ResourceManager.GetObject("cross-circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross_script {
            get {
                object obj = ResourceManager.GetObject("cross_script", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cross_small {
            get {
                object obj = ResourceManager.GetObject("cross_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database__arrow {
            get {
                object obj = ResourceManager.GetObject("database__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_share {
            get {
                object obj = ResourceManager.GetObject("database_share", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk__arrow {
            get {
                object obj = ResourceManager.GetObject("disk__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disks {
            get {
                object obj = ResourceManager.GetObject("disks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document {
            get {
                object obj = ResourceManager.GetObject("document", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document__arrow {
            get {
                object obj = ResourceManager.GetObject("document__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document__plus {
            get {
                object obj = ResourceManager.GetObject("document__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_code {
            get {
                object obj = ResourceManager.GetObject("document_code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_copy {
            get {
                object obj = ResourceManager.GetObject("document_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_search_result {
            get {
                object obj = ResourceManager.GetObject("document_search_result", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Editor: {0}.
        /// </summary>
        internal static string EditorRegistered {
            get {
                return ResourceManager.GetString("EditorRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleton view content cannot be closed by users. The AllowUserClose property must return false.
        /// </summary>
        internal static string Error_Closeable_Singleton_Content {
            get {
                return ResourceManager.GetString("Error_Closeable_Singleton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified view content type is not registered in any addin files: {0}.
        /// </summary>
        internal static string Error_ViewContent_Not_Registered {
            get {
                return ResourceManager.GetString("Error_ViewContent_Not_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified view content type is not a singleton: {0}.
        /// </summary>
        internal static string Error_ViewContent_Type_Not_Singleton {
            get {
                return ResourceManager.GetString("Error_ViewContent_Type_Not_Singleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodesk DWF (*.dwf)|*.dwf.
        /// </summary>
        internal static string Filter_Dwf_Files {
            get {
                return ResourceManager.GetString("Filter_Dwf_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapGuide Package File (*.mgp)|*.mgp.
        /// </summary>
        internal static string Filter_Mgp_Files {
            get {
                return ResourceManager.GetString("Filter_Mgp_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodesk SDF (*.sdf)|*.sdf.
        /// </summary>
        internal static string Filter_Sdf_Files {
            get {
                return ResourceManager.GetString("Filter_Sdf_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESRI Shapefile (*.shp)|*.shp.
        /// </summary>
        internal static string Filter_Shp_Files {
            get {
                return ResourceManager.GetString("Filter_Shp_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables|*.exe.
        /// </summary>
        internal static string FilterExecutables {
            get {
                return ResourceManager.GetString("FilterExecutables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation detected errors in your resource, please fix them before saving this resource.
        /// </summary>
        internal static string FixErrorsBeforeSaving {
            get {
                return ResourceManager.GetString("FixErrorsBeforeSaving", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap folder__plus {
            get {
                object obj = ResourceManager.GetObject("folder__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_horizontal {
            get {
                object obj = ResourceManager.GetObject("folder_horizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Global_ErrorText {
            get {
                return ResourceManager.GetString("Global.ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Global_QuestionText {
            get {
                return ResourceManager.GetString("Global.QuestionText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap images_stack {
            get {
                object obj = ResourceManager.GetObject("images_stack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items copied and placed in clipboard.
        /// </summary>
        internal static string ItemsCopied {
            get {
                return ResourceManager.GetString("ItemsCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items cut and placed in clipboard.
        /// </summary>
        internal static string ItemsCut {
            get {
                return ResourceManager.GetString("ItemsCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items migrated.
        /// </summary>
        internal static string ItemsMigrated {
            get {
                return ResourceManager.GetString("ItemsMigrated", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap layer {
            get {
                object obj = ResourceManager.GetObject("layer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the sub-layer type or this type is not currently supported.
        /// </summary>
        internal static string LayerSubTypeNotSupported {
            get {
                return ResourceManager.GetString("LayerSubTypeNotSupported", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Feature Source Preview.
        /// </summary>
        internal static string LocalFsPreview {
            get {
                return ResourceManager.GetString("LocalFsPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate executable: {0}.
        /// </summary>
        internal static string LocateExecutable {
            get {
                return ResourceManager.GetString("LocateExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Log saved to {0}.
        /// </summary>
        internal static string Log_Saved {
            get {
                return ResourceManager.GetString("Log_Saved", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon MapGuide_Maestro {
            get {
                object obj = ResourceManager.GetObject("MapGuide_Maestro", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("Menu_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Menu_Edit_Cut {
            get {
                return ResourceManager.GetString("Menu_Edit_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Menu_Edit_Paste {
            get {
                return ResourceManager.GetString("Menu_Edit_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Active Document.
        /// </summary>
        internal static string Menu_File_CloseActiveDocument {
            get {
                return ResourceManager.GetString("Menu_File_CloseActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Documents.
        /// </summary>
        internal static string Menu_File_CloseAll {
            get {
                return ResourceManager.GetString("Menu_File_CloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Menu_File_Connect {
            get {
                return ResourceManager.GetString("Menu_File_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Resource.
        /// </summary>
        internal static string Menu_File_DeleteResource {
            get {
                return ResourceManager.GetString("Menu_File_DeleteResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Resource with XML Editor.
        /// </summary>
        internal static string Menu_File_EditResourceWithXml {
            get {
                return ResourceManager.GetString("Menu_File_EditResourceWithXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Menu_File_Login {
            get {
                return ResourceManager.GetString("Menu_File_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Resource.
        /// </summary>
        internal static string Menu_File_NewResource {
            get {
                return ResourceManager.GetString("Menu_File_NewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Resource.
        /// </summary>
        internal static string Menu_File_PreviewResource {
            get {
                return ResourceManager.GetString("Menu_File_PreviewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Resource.
        /// </summary>
        internal static string Menu_File_ProfileResource {
            get {
                return ResourceManager.GetString("Menu_File_ProfileResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Menu_File_Quit {
            get {
                return ResourceManager.GetString("Menu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        internal static string Menu_File_SaveAll {
            get {
                return ResourceManager.GetString("Menu_File_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Resource.
        /// </summary>
        internal static string Menu_File_SaveResource {
            get {
                return ResourceManager.GetString("Menu_File_SaveResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Resource As.
        /// </summary>
        internal static string Menu_File_SaveResourceAs {
            get {
                return ResourceManager.GetString("Menu_File_SaveResourceAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Resource.
        /// </summary>
        internal static string Menu_File_ValidateResource {
            get {
                return ResourceManager.GetString("Menu_File_ValidateResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string Menu_Package {
            get {
                return ResourceManager.GetString("Menu_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Package.
        /// </summary>
        internal static string Menu_Package_LoadPackage {
            get {
                return ResourceManager.GetString("Menu_Package_LoadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Menu_Tools {
            get {
                return ResourceManager.GetString("Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Menu_Tools_Options {
            get {
                return ResourceManager.GetString("Menu_Tools_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Log.
        /// </summary>
        internal static string Menu_View_MessageLog {
            get {
                return ResourceManager.GetString("Menu_View_MessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        internal static string Menu_Window {
            get {
                return ResourceManager.GetString("Menu_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MgCooker.
        /// </summary>
        internal static string MgCooker {
            get {
                return ResourceManager.GetString("MgCooker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load this package file.
        /// </summary>
        internal static string MgpHandlerAction {
            get {
                return ResourceManager.GetString("MgpHandlerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move {0} to {1}.
        /// </summary>
        internal static string MoveFailure {
            get {
                return ResourceManager.GetString("MoveFailure", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap navigation {
            get {
                object obj = ResourceManager.GetObject("navigation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_000_white {
            get {
                object obj = ResourceManager.GetObject("navigation-000-white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_180 {
            get {
                object obj = ResourceManager.GetObject("navigation-180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_180_white {
            get {
                object obj = ResourceManager.GetObject("navigation-180-white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Map.
        /// </summary>
        internal static string NewMap {
            get {
                return ResourceManager.GetString("NewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Resource.
        /// </summary>
        internal static string NewResource {
            get {
                return ResourceManager.GetString("NewResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource ID must not be session based.
        /// </summary>
        internal static string NotSessionBasedId {
            get {
                return ResourceManager.GetString("NotSessionBasedId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping registration of editor: {0} because an existing editor is already registered to handle {1} v{2}.
        /// </summary>
        internal static string OpenResourceManager_SkipEditorRegistration {
            get {
                return ResourceManager.GetString("OpenResourceManager_SkipEditorRegistration", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap plug__arrow {
            get {
                object obj = ResourceManager.GetObject("plug__arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plug__minus {
            get {
                object obj = ResourceManager.GetObject("plug--minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plug__plus {
            get {
                object obj = ResourceManager.GetObject("plug__plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Prefs_General {
            get {
                return ResourceManager.GetString("Prefs_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A restart is required for some changes to take effect. Restart now?.
        /// </summary>
        internal static string PrefsRestartRequired {
            get {
                return ResourceManager.GetString("PrefsRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Map.
        /// </summary>
        internal static string PreviewMap {
            get {
                return ResourceManager.GetString("PreviewMap", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating References.
        /// </summary>
        internal static string ProgressUpdatingReferences {
            get {
                return ResourceManager.GetString("ProgressUpdatingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename to.
        /// </summary>
        internal static string RenameTo {
            get {
                return ResourceManager.GetString("RenameTo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap reports_stack {
            get {
                object obj = ResourceManager.GetObject("reports_stack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource is already opened in another editor.
        /// </summary>
        internal static string ResourceAlreadyOpened {
            get {
                return ResourceManager.GetString("ResourceAlreadyOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Migrated: {0}.
        /// </summary>
        internal static string ResourceMigrated {
            get {
                return ResourceManager.GetString("ResourceMigrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This selected resource is not re-pointable.
        /// </summary>
        internal static string ResourceNotRepointable {
            get {
                return ResourceManager.GetString("ResourceNotRepointable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resources re-pointed to {1}.
        /// </summary>
        internal static string ResourcesRepointed {
            get {
                return ResourceManager.GetString("ResourcesRepointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decode the current bounds,
        ///you must re-enter the epsg code in the SRS tag manually.
        ///Error message: {0}..
        /// </summary>
        internal static string ResProp_BoundsDecodeError {
            get {
                return ResourceManager.GetString("ResProp_BoundsDecodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must manually enter the EPSG code for the generated bounds..
        /// </summary>
        internal static string ResProp_EpsgMissingWarning {
            get {
                return ResourceManager.GetString("ResProp_EpsgMissingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        internal static string ResProp_InheritedAccess {
            get {
                return ResourceManager.GetString("ResProp_InheritedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing bounds tag.
        /// </summary>
        internal static string ResProp_MissingBoundsError {
            get {
                return ResourceManager.GetString("ResProp_MissingBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access.
        /// </summary>
        internal static string ResProp_NoAccess {
            get {
                return ResourceManager.GetString("ResProp_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spatial data found in FeatureSource.
        /// </summary>
        internal static string ResProp_NoSpatialDataError {
            get {
                return ResourceManager.GetString("ResProp_NoSpatialDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spatial data found in FeatureSource, one or more queries failed to execute.
        /// </summary>
        internal static string ResProp_NoSpatialDataWithFailuresError {
            get {
                return ResourceManager.GetString("ResProp_NoSpatialDataWithFailuresError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only.
        /// </summary>
        internal static string ResProp_ReadOnlyAccess {
            get {
                return ResourceManager.GetString("ResProp_ReadOnlyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/write.
        /// </summary>
        internal static string ResProp_ReadWriteAccess {
            get {
                return ResourceManager.GetString("ResProp_ReadWriteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read resource references.
        /// </summary>
        internal static string ResProp_ReferenceReadError {
            get {
                return ResourceManager.GetString("ResProp_ReferenceReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read resource references: {0}.
        /// </summary>
        internal static string ResProp_ReferenceReadSpecificError {
            get {
                return ResourceManager.GetString("ResProp_ReferenceReadSpecificError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the resource properties: {0}.
        /// </summary>
        internal static string ResProp_SaveError {
            get {
                return ResourceManager.GetString("ResProp_SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain the extent for the WFS data.
        ///Error message: {0}.
        /// </summary>
        internal static string ResProp_WFSBoundsReadError {
            get {
                return ResourceManager.GetString("ResProp_WFSBoundsReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain the extent for the WMS data.
        ///Error message: {0}.
        /// </summary>
        internal static string ResProp_WMSBoundsReadError {
            get {
                return ResourceManager.GetString("ResProp_WMSBoundsReadError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap scissors_blue {
            get {
                object obj = ResourceManager.GetObject("scissors_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a SDF Feature Source.
        /// </summary>
        internal static string SdfHandlerAction {
            get {
                return ResourceManager.GetString("SdfHandlerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FDO Provider.
        /// </summary>
        internal static string SelectFdoProvider {
            get {
                return ResourceManager.GetString("SelectFdoProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the user template path.
        /// </summary>
        internal static string SelectTemplatePath {
            get {
                return ResourceManager.GetString("SelectTemplatePath", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap server {
            get {
                object obj = ResourceManager.GetObject("server", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Status Monitor.
        /// </summary>
        internal static string ServerMonitor {
            get {
                return ResourceManager.GetString("ServerMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized: Open Resource Manager.
        /// </summary>
        internal static string Service_Init_Open_Resource_Manager {
            get {
                return ResourceManager.GetString("Service_Init_Open_Resource_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized: Server Connection Manager.
        /// </summary>
        internal static string Service_Init_Server_Connection_Manager {
            get {
                return ResourceManager.GetString("Service_Init_Server_Connection_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized: URL Launcher.
        /// </summary>
        internal static string Service_Init_Url_Launcher {
            get {
                return ResourceManager.GetString("Service_Init_Url_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized: View Content Manager.
        /// </summary>
        internal static string Service_Init_ViewContent_Manager {
            get {
                return ResourceManager.GetString("Service_Init_ViewContent_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a SHP Feature Source.
        /// </summary>
        internal static string ShpHandlerAction {
            get {
                return ResourceManager.GetString("ShpHandlerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Name: {1}{0}Resource Type: {2}{0}Created: {3}{0}Last Modified: {4}{0}Owner: {5}.
        /// </summary>
        internal static string SITE_EXPLORER_TOOLTIP_TEMPLATE {
            get {
                return ResourceManager.GetString("SITE_EXPLORER_TOOLTIP_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy/Move selected items to another server.
        /// </summary>
        internal static string SiteExplorer_CopyMoveToServer {
            get {
                return ResourceManager.GetString("SiteExplorer_CopyMoveToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string SiteExplorer_Disconnect {
            get {
                return ResourceManager.GetString("SiteExplorer_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate.
        /// </summary>
        internal static string SiteExplorer_Migrate {
            get {
                return ResourceManager.GetString("SiteExplorer_Migrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string SiteExplorer_NewFolder {
            get {
                return ResourceManager.GetString("SiteExplorer_NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string SiteExplorer_Refresh {
            get {
                return ResourceManager.GetString("SiteExplorer_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repoint this resource.
        /// </summary>
        internal static string SiteExplorer_Repoint {
            get {
                return ResourceManager.GetString("SiteExplorer_Repoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package folder.
        /// </summary>
        internal static string SiteExplorer_SelectedFolder_CreatePackage {
            get {
                return ResourceManager.GetString("SiteExplorer_SelectedFolder_CreatePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste into this folder.
        /// </summary>
        internal static string SiteExplorer_SelectedFolder_Paste {
            get {
                return ResourceManager.GetString("SiteExplorer_SelectedFolder_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected item(s).
        /// </summary>
        internal static string SiteExplorer_SelectedItem_Copy {
            get {
                return ResourceManager.GetString("SiteExplorer_SelectedItem_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selected items(s).
        /// </summary>
        internal static string SiteExplorer_SelectedItem_Cut {
            get {
                return ResourceManager.GetString("SiteExplorer_SelectedItem_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item(s).
        /// </summary>
        internal static string SiteExplorer_SelectedItem_Delete {
            get {
                return ResourceManager.GetString("SiteExplorer_SelectedItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string SiteExplorer_SelectedItem_Open {
            get {
                return ResourceManager.GetString("SiteExplorer_SelectedItem_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Resource with XML Editor.
        /// </summary>
        internal static string SiteExplorer_SelectedItem_OpenWithXmlEditor {
            get {
                return ResourceManager.GetString("SiteExplorer_SelectedItem_OpenWithXmlEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string SiteExplorer_SelectedItem_Properties {
            get {
                return ResourceManager.GetString("SiteExplorer_SelectedItem_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string SiteExplorer_SelectedItem_Rename {
            get {
                return ResourceManager.GetString("SiteExplorer_SelectedItem_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string SiteExplorer_ValidateResources {
            get {
                return ResourceManager.GetString("SiteExplorer_ValidateResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a SQLite Feature Source.
        /// </summary>
        internal static string SltHandlerAction {
            get {
                return ResourceManager.GetString("SltHandlerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this tab.
        /// </summary>
        internal static string TabClose {
            get {
                return ResourceManager.GetString("TabClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all tabs except this.
        /// </summary>
        internal static string TabCloseExceptThis {
            get {
                return ResourceManager.GetString("TabCloseExceptThis", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tick {
            get {
                object obj = ResourceManager.GetObject("tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Fusion Application Definition (Flexible Layout).
        /// </summary>
        internal static string TPL_ADF_DESC {
            get {
                return ResourceManager.GetString("TPL_ADF_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Definition.
        /// </summary>
        internal static string TPL_ADF_NAME {
            get {
                return ResourceManager.GetString("TPL_ADF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string TPL_CATEGORY_DEFAULT {
            get {
                return ResourceManager.GetString("TPL_CATEGORY_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        internal static string TPL_CATEGORY_USERDEF {
            get {
                return ResourceManager.GetString("TPL_CATEGORY_USERDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Compund Symbol Definition.
        /// </summary>
        internal static string TPL_CSD_DESC {
            get {
                return ResourceManager.GetString("TPL_CSD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Symbol Definition.
        /// </summary>
        internal static string TPL_CSD_NAME {
            get {
                return ResourceManager.GetString("TPL_CSD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Drawing Layer Definition.
        /// </summary>
        internal static string TPL_DLDF_DESC {
            get {
                return ResourceManager.GetString("TPL_DLDF_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Layer Definition.
        /// </summary>
        internal static string TPL_DLDF_NAME {
            get {
                return ResourceManager.GetString("TPL_DLDF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Drawing Source.
        /// </summary>
        internal static string TPL_DS_DESC {
            get {
                return ResourceManager.GetString("TPL_DS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Source.
        /// </summary>
        internal static string TPL_DS_NAME {
            get {
                return ResourceManager.GetString("TPL_DS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Feature Source.
        /// </summary>
        internal static string TPL_FS_DESC {
            get {
                return ResourceManager.GetString("TPL_FS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Source.
        /// </summary>
        internal static string TPL_FS_NAME {
            get {
                return ResourceManager.GetString("TPL_FS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a DWF Load Procedure.
        /// </summary>
        internal static string TPL_LP_DWF_DESC {
            get {
                return ResourceManager.GetString("TPL_LP_DWF_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWF Load Procedure.
        /// </summary>
        internal static string TPL_LP_DWF_NAME {
            get {
                return ResourceManager.GetString("TPL_LP_DWF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new SDF Load Procedure.
        /// </summary>
        internal static string TPL_LP_SDF_DESC {
            get {
                return ResourceManager.GetString("TPL_LP_SDF_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDF Load Procedure.
        /// </summary>
        internal static string TPL_LP_SDF_NAME {
            get {
                return ResourceManager.GetString("TPL_LP_SDF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new SHP Load Procedure.
        /// </summary>
        internal static string TPL_LP_SHP_DESC {
            get {
                return ResourceManager.GetString("TPL_LP_SHP_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHP Load Procedure.
        /// </summary>
        internal static string TPL_LP_SHP_NAME {
            get {
                return ResourceManager.GetString("TPL_LP_SHP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Map Definition.
        /// </summary>
        internal static string TPL_MDF_DESC {
            get {
                return ResourceManager.GetString("TPL_MDF_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Definition.
        /// </summary>
        internal static string TPL_MDF_NAME {
            get {
                return ResourceManager.GetString("TPL_MDF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Print Layout.
        /// </summary>
        internal static string TPL_PL_DESC {
            get {
                return ResourceManager.GetString("TPL_PL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Layout.
        /// </summary>
        internal static string TPL_PL_NAME {
            get {
                return ResourceManager.GetString("TPL_PL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Raster Layer Definition using the v1.0.0 schema.
        /// </summary>
        internal static string TPL_RLDF_DESC {
            get {
                return ResourceManager.GetString("TPL_RLDF_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster Layer Definition (v1.0.0).
        /// </summary>
        internal static string TPL_RLDF_NAME {
            get {
                return ResourceManager.GetString("TPL_RLDF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Simple Symbol Definition.
        /// </summary>
        internal static string TPL_SSD_DESC {
            get {
                return ResourceManager.GetString("TPL_SSD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Symbol Definition.
        /// </summary>
        internal static string TPL_SSD_NAME {
            get {
                return ResourceManager.GetString("TPL_SSD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Resource Template.
        /// </summary>
        internal static string TPL_USER_DEFINED {
            get {
                return ResourceManager.GetString("TPL_USER_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Vector Layer Definition using the v1.0.0 schema.
        /// </summary>
        internal static string TPL_VLDF_DESC {
            get {
                return ResourceManager.GetString("TPL_VLDF_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vector Layer Definition (v1.0.0).
        /// </summary>
        internal static string TPL_VLDF_NAME {
            get {
                return ResourceManager.GetString("TPL_VLDF_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Web Layout using the v1.0.0 schema.
        /// </summary>
        internal static string TPL_WL_DESC {
            get {
                return ResourceManager.GetString("TPL_WL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Layout (v1.0.0).
        /// </summary>
        internal static string TPL_WL_NAME {
            get {
                return ResourceManager.GetString("TPL_WL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type cannot be previewed.
        /// </summary>
        internal static string UnpreviewableResourceType {
            get {
                return ResourceManager.GetString("UnpreviewableResourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building resource list....
        /// </summary>
        internal static string ValidationBuildingList {
            get {
                return ResourceManager.GetString("ValidationBuildingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file: {0}.
        /// </summary>
        internal static string ValidationFailedError {
            get {
                return ResourceManager.GetString("ValidationFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issues found during validation.
        /// </summary>
        internal static string ValidationNoIssues {
            get {
                return ResourceManager.GetString("ValidationNoIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating resource: {0}.
        /// </summary>
        internal static string ValidationProgressMessage {
            get {
                return ResourceManager.GetString("ValidationProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load resource: {0}.
        /// </summary>
        internal static string ValidationResourceLoadFailed {
            get {
                return ResourceManager.GetString("ValidationResourceLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}: {2}.
        /// </summary>
        internal static string ValidationResultFormat {
            get {
                return ResourceManager.GetString("ValidationResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating ....
        /// </summary>
        internal static string ValidationValidating {
            get {
                return ResourceManager.GetString("ValidationValidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Editor:.
        /// </summary>
        internal static string XmlEditor {
            get {
                return ResourceManager.GetString("XmlEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load this resource into the Site Repository.
        /// </summary>
        internal static string XmlResHandlerAction {
            get {
                return ResourceManager.GetString("XmlResHandlerAction", resourceCulture);
            }
        }
    }
}
