//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.MapGuide.Maestro.ResourceEditors.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorBrewer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorBrewer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.MapGuide.Maestro.ResourceEditors.Strings.ColorBrewer", typeof(ColorBrewer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read {0} color(s) in line {1}.
        /// </summary>
        internal static string ColorCountError {
            get {
                return ResourceManager.GetString("ColorCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diverging.
        /// </summary>
        internal static string DivergingName {
            get {
                return ResourceManager.GetString("DivergingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} color component {1} in line {2}.
        /// </summary>
        internal static string InvalidColorComponent {
            get {
                return ResourceManager.GetString("InvalidColorComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field count in line {0}.
        /// </summary>
        internal static string InvalidFieldCountError {
            get {
                return ResourceManager.GetString("InvalidFieldCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid record count in line {0}.
        /// </summary>
        internal static string InvalidRecordCountError {
            get {
                return ResourceManager.GetString("InvalidRecordCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing column &quot;{0}&quot;.
        /// </summary>
        internal static string MissingColumnError {
            get {
                return ResourceManager.GetString("MissingColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitative.
        /// </summary>
        internal static string QualitativeName {
            get {
                return ResourceManager.GetString("QualitativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequential.
        /// </summary>
        internal static string SequentialName {
            get {
                return ResourceManager.GetString("SequentialName", resourceCulture);
            }
        }
    }
}
