//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.MapGuide.Maestro.ResourceEditors.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.MapGuide.Maestro.ResourceEditors.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access database (*.mdb).
        /// </summary>
        internal static string AccessDatabaseFiles {
            get {
                return ResourceManager.GetString("AccessDatabaseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*).
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII file (*.asc).
        /// </summary>
        internal static string ASCIIFiles {
            get {
                return ResourceManager.GetString("ASCIIFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed while reading data from assembly.
        /// </summary>
        internal static string AssemblyDataInternalError {
            get {
                return ResourceManager.GetString("AssemblyDataInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated values (*.csv).
        /// </summary>
        internal static string CSVFiles {
            get {
                return ResourceManager.GetString("CSVFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dBase database (*.dbf).
        /// </summary>
        internal static string dBaseFiles {
            get {
                return ResourceManager.GetString("dBaseFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DGN file (*.dgn).
        /// </summary>
        internal static string DGNFiles {
            get {
                return ResourceManager.GetString("DGNFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string EmptyText {
            get {
                return ResourceManager.GetString("EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel spreadsheet (*.xls).
        /// </summary>
        internal static string ExcelFiles {
            get {
                return ResourceManager.GetString("ExcelFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firebird database (*.fdb).
        /// </summary>
        internal static string FirebirdFiles {
            get {
                return ResourceManager.GetString("FirebirdFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured: {0}.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GML file (*.gml).
        /// </summary>
        internal static string GMLFiles {
            get {
                return ResourceManager.GetString("GMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infinite.
        /// </summary>
        internal static string InfiniteValue {
            get {
                return ResourceManager.GetString("InfiniteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string InvalidValueError {
            get {
                return ResourceManager.GetString("InvalidValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KML file (*.kml).
        /// </summary>
        internal static string KMLFiles {
            get {
                return ResourceManager.GetString("KMLFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapInfo Interchange (*.mif).
        /// </summary>
        internal static string MapInfoInterchangeFiles {
            get {
                return ResourceManager.GetString("MapInfoInterchangeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapInfo Native (*.tab).
        /// </summary>
        internal static string MapInfoNativeFiles {
            get {
                return ResourceManager.GetString("MapInfoNativeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not yet implemented.
        /// </summary>
        internal static string MissingMethod {
            get {
                return ResourceManager.GetString("MissingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-57 (*.s57).
        /// </summary>
        internal static string S57Files {
            get {
                return ResourceManager.GetString("S57Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDF files (*.sdf).
        /// </summary>
        internal static string SDFFiles {
            get {
                return ResourceManager.GetString("SDFFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape file (*.shp).
        /// </summary>
        internal static string ShapeFiles {
            get {
                return ResourceManager.GetString("ShapeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite3 files (*.sqlite3).
        /// </summary>
        internal static string SQLite3Files {
            get {
                return ResourceManager.GetString("SQLite3Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite database (*.db).
        /// </summary>
        internal static string SQLiteDbFiles {
            get {
                return ResourceManager.GetString("SQLiteDbFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite database (*.sqlite).
        /// </summary>
        internal static string SQLiteFiles {
            get {
                return ResourceManager.GetString("SQLiteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabulator seperated values (*.tab).
        /// </summary>
        internal static string TABFiles {
            get {
                return ResourceManager.GetString("TABFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file (*.txt).
        /// </summary>
        internal static string TextFiles {
            get {
                return ResourceManager.GetString("TextFiles", resourceCulture);
            }
        }
    }
}
