//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.MapGuide.Maestro.ResourceEditors.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LayoutEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.MapGuide.Maestro.ResourceEditors.Strings.LayoutEditor", typeof(LayoutEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed while reading data from assembly.
        /// </summary>
        internal static string AssemblyReadError {
            get {
                return ResourceManager.GetString("AssemblyReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch browser: {0}.
        /// </summary>
        internal static string BrowserLaunchError {
            get {
                return ResourceManager.GetString("BrowserLaunchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get avalible command name.
        /// </summary>
        internal static string CommandNameLookupError {
            get {
                return ResourceManager.GetString("CommandNameLookupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function is not yet implemented.
        /// </summary>
        internal static string FunctionNotSupportedError {
            get {
                return ResourceManager.GetString("FunctionNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New submenu.
        /// </summary>
        internal static string NewSubmenuName {
            get {
                return ResourceManager.GetString("NewSubmenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Separator.
        /// </summary>
        internal static string SeparatorName {
            get {
                return ResourceManager.GetString("SeparatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Taskbar does not support sub menus.
        /// </summary>
        internal static string SubMenuInTaskBarError {
            get {
                return ResourceManager.GetString("SubMenuInTaskBarError", resourceCulture);
            }
        }
    }
}
