//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.MapGuide.MaestroAPI.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.MapGuide.MaestroAPI.Tests.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://fdo.osgeo.org/schemas/feature/OGRSchema&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:OGRSchema=&quot;http://fdo.osgeo.org/schemas/feature/OGRSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///    &lt;xs:element name=&quot;catasto-x7e-fabbricati&quot; type=&quot;OGRSchema:catasto-x7e-fabbricatiType&quot; abstract=&quot;false&quot; substitutionGroup=&quot;gml:_Feature [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1896 {
            get {
                return ResourceManager.GetString("_1896", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FeatureSet&gt;
        ///    &lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://fdo.osgeo.org/schemas/feature/TempSchema&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:TempSchema=&quot;http://fdo.osgeo.org/schemas/feature/TempSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///        &lt;xs:annotation&gt;
        ///            &lt;xs:documentation /&gt;
        ///        &lt;/xs:annotation&gt;
        ///        &lt;xs:complexType name=&quot;Par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FeatureJoinSelectSample {
            get {
                return ResourceManager.GetString("FeatureJoinSelectSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://fdo.osgeo.org/schemas/feature/AutoGen&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:gml=&quot;http://www.opengis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gen_default1_MySql_master {
            get {
                return ResourceManager.GetString("gen_default1_MySql_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///&lt;gml:DerivedCRS gml:id=&quot;sc_1&quot;&gt;
        ///&lt;gml:metaDataProperty&gt;
        ///&lt;gml:GenericMetaData&gt;
        ///&lt;fdo:XYTolerance&gt;
        ///0.001000&lt;/fdo:XYTolerance&gt;
        ///&lt;/gml:GenericMetaData&gt;
        ///&lt;/gml:metaDataProperty&gt;
        ///&lt;gml:remarks&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gen_default1_Oracle_master {
            get {
                return ResourceManager.GetString("gen_default1_Oracle_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://fdo.osgeo.org/schemas/feature/dbo&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:gml=&quot;http://www.opengis.net [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gen_default1_SqlServer_master {
            get {
                return ResourceManager.GetString("gen_default1_SqlServer_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://fdo.osgeo.org/schemas/feature/dbo&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:gml=&quot;http://www.opengis.net [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gen_default1_SqlServer2005_master {
            get {
                return ResourceManager.GetString("gen_default1_SqlServer2005_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://fdo.osgeo.org/schemas/feature/dbo&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:gml=&quot;http://www.opengis.net [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gen_default1_SqlServer2008_master {
            get {
                return ResourceManager.GetString("gen_default1_SqlServer2008_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://fdo.osgeo.org/schemas/feature/dbo&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:gml=&quot;http://www.opengis.net [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gen_default1_SQLServerSpatial_master {
            get {
                return ResourceManager.GetString("gen_default1_SQLServerSpatial_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;LayerDefinition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;LayerDefinition-1.2.0.xsd&quot; version=&quot;1.2.0&quot;&gt;
        ///  &lt;VectorLayerDefinition&gt;
        ///    &lt;ResourceId&gt;Library://IDontExist.FeatureSource&lt;/ResourceId&gt;
        ///    &lt;FeatureName&gt;SHP_Schema:Rail&lt;/FeatureName&gt;
        ///    &lt;FeatureNameType&gt;FeatureClass&lt;/FeatureNameType&gt;
        ///    &lt;Geometry&gt;SHPGEOM&lt;/Geometry&gt;
        ///    &lt;VectorScaleRange&gt;
        ///      &lt;LineTypeStyle&gt;
        ///        &lt;LineRule&gt;
        ///          &lt;LegendLabel /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InvalidLayer {
            get {
                return ResourceManager.GetString("InvalidLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- This configuration document is from the Fdo WMS notes (http://trac.osgeo.org/fdo/wiki/FdoWmsNotes) --&gt;
        ///&lt;fdo:DataStore xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://fdo.osgeo.org/schemas&quot; xsi:schemaLocation=&quot;http://fdo.osgeo.org/schemas FdoDocument.xsd&quot;&gt;
        ///  &lt;xs:schema xmlns:xs= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NASA_WMS_config_doc {
            get {
                return ResourceManager.GetString("NASA_WMS_config_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!-- Sample ODBC config document from Trac ticket #1478 --&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///  &lt;gml:DerivedCRS gml:id=&quot;CSRS.UTM-20N&quot;&gt;
        ///    &lt;gml:remarks&gt;CSRS.UTM-20N&lt;/gml:remarks&gt;
        ///    &lt;gml:srsName&gt;CSRS.UTM-20N&lt;/gml:srsNam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string odbc_example_config {
            get {
                return ResourceManager.GetString("odbc_example_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///  &lt;gml:DerivedCRS gml:id=&quot;CSRS.UTM-20N&quot;&gt;
        ///    &lt;gml:remarks&gt;CSRS.UTM-20N&lt;/gml:remarks&gt;
        ///    &lt;gml:srsName&gt;CSRS.UTM-20N&lt;/gml:srsName&gt;
        ///    &lt;!-- TODO: Maestro does not know how to read the coor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string odbc_example_config2 {
            get {
                return ResourceManager.GetString("odbc_example_config2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;PropertySet&gt;
        ///    &lt;PropertyDefinitions&gt;
        ///        &lt;PropertyDefinition&gt;
        ///            &lt;Name&gt;ID&lt;/Name&gt;
        ///            &lt;Type&gt;int32&lt;/Type&gt;
        ///        &lt;/PropertyDefinition&gt;
        ///        &lt;PropertyDefinition&gt;
        ///            &lt;Name&gt;Name&lt;/Name&gt;
        ///            &lt;Type&gt;string&lt;/Type&gt;
        ///        &lt;/PropertyDefinition&gt;
        ///        &lt;PropertyDefinition&gt;
        ///            &lt;Name&gt;URL&lt;/Name&gt;
        ///            &lt;Type&gt;string&lt;/Type&gt;
        ///        &lt;/PropertyDefinition&gt;
        ///    &lt;/PropertyDefinitions&gt;
        ///    &lt;Properties&gt;
        ///        &lt;Prop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectAggregatesSample {
            get {
                return ResourceManager.GetString("SelectAggregatesSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;FeatureSet&gt;
        ///    &lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://fdo.osgeo.org/schemas/feature/Schema1&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:Schema1=&quot;http://fdo.osgeo.org/schemas/feature/Schema1&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///        &lt;xs:annotation&gt;
        ///            &lt;xs:documentation /&gt;
        ///            &lt;xs:appinfo source=&quot;http://fdo.osgeo.org/schemas&quot; /&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectFeatureSample {
            get {
                return ResourceManager.GetString("SelectFeatureSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;RowSet&gt;
        ///    &lt;ColumnDefinitions&gt;
        ///        &lt;Column&gt;
        ///            &lt;Name&gt;ID&lt;/Name&gt;
        ///            &lt;Type&gt;int32&lt;/Type&gt;
        ///        &lt;/Column&gt;
        ///        &lt;Column&gt;
        ///            &lt;Name&gt;Name&lt;/Name&gt;
        ///            &lt;Type&gt;string&lt;/Type&gt;
        ///        &lt;/Column&gt;
        ///        &lt;Column&gt;
        ///            &lt;Name&gt;URL&lt;/Name&gt;
        ///            &lt;Type&gt;string&lt;/Type&gt;
        ///        &lt;/Column&gt;
        ///    &lt;/ColumnDefinitions&gt;
        ///    &lt;Rows&gt;
        ///        &lt;Row&gt;
        ///            &lt;Column&gt;
        ///                &lt;Name&gt;ID&lt;/Name&gt;
        ///                &lt;Value&gt;1&lt;/Valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectSqlSample {
            get {
                return ResourceManager.GetString("SelectSqlSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;LayerDefinition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; version=&quot;1.0.0&quot; xsi:noNamespaceSchemaLocation=&quot;LayerDefinition-1.0.0.xsd&quot;&gt;
        ///  &lt;DrawingLayerDefinition&gt;
        ///    &lt;ResourceId&gt;Library://UnitTests/Data/SpaceShip.DrawingSource&lt;/ResourceId&gt;
        ///    &lt;Sheet&gt;com.autodesk.dwf.ePlot_9E2723744244DB8C44482263E654F764&lt;/Sheet&gt;
        ///    &lt;LayerFilter&gt;YELLOW,CYAN,GREEN,RED,BLUE,WHITE&lt;/LayerFilter&gt;
        ///  &lt;/DrawingLayerDefinition&gt;
        ///&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpaceShip {
            get {
                return ResourceManager.GetString("SpaceShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;MapDefinition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xsi:noNamespaceSchemaLocation=&quot;MapDefinition-1.0.0.xsd&quot;&gt;
        ///    &lt;Name&gt;New Map&lt;/Name&gt;
        ///    &lt;CoordinateSystem&gt;GEOGCS[&quot;WGS84 Lat/Long&apos;s, Degrees, -180 ==&amp;gt; +180&quot;,DATUM[&quot;D_WGS_1984&quot;,SPHEROID[&quot;World_Geodetic_System_of_1984&quot;,6378137,298.257222932867]],PRIMEM[&quot;Greenwich&quot;,0],UNIT[&quot;Degree&quot;,0.017453292519943295]]&lt;/CoordinateSystem&gt;
        ///    &lt;Extents&gt;
        ///        &lt;MinX&gt;-87. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDuplicateLayerIds {
            get {
                return ResourceManager.GetString("TestDuplicateLayerIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;MapDefinition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xsi:noNamespaceSchemaLocation=&quot;MapDefinition-1.0.0.xsd&quot;&gt;
        ///  &lt;Name&gt;New Map&lt;/Name&gt;
        ///  &lt;CoordinateSystem&gt;GEOGCS[&quot;WGS84 Lat/Long&apos;s, Degrees, -180 ==&gt; +180&quot;,DATUM[&quot;D_WGS_1984&quot;,SPHEROID[&quot;World_Geodetic_System_of_1984&quot;,6378137,298.257222932867]],PRIMEM[&quot;Greenwich&quot;,0],UNIT[&quot;Degree&quot;,0.017453292519943295]]&lt;/CoordinateSystem&gt;
        ///  &lt;Extents&gt;
        ///    &lt;MinX&gt;-87.770746109180749&lt;/MinX&gt;
        ///    &lt;MaxX&gt;-87.6957605384125&lt;/MaxX&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestMapWithInvalidLayers {
            get {
                return ResourceManager.GetString("TestMapWithInvalidLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;MapDefinition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xsi:noNamespaceSchemaLocation=&quot;MapDefinition-1.0.0.xsd&quot;&gt;
        ///    &lt;Name&gt;New Map&lt;/Name&gt;
        ///    &lt;CoordinateSystem&gt;GEOGCS[&quot;WGS84 Lat/Long&apos;s, Degrees, -180 ==&amp;gt; +180&quot;,DATUM[&quot;D_WGS_1984&quot;,SPHEROID[&quot;World_Geodetic_System_of_1984&quot;,6378137,298.257222932867]],PRIMEM[&quot;Greenwich&quot;,0],UNIT[&quot;Degree&quot;,0.017453292519943295]]&lt;/CoordinateSystem&gt;
        ///    &lt;Extents&gt;
        ///        &lt;MinX&gt;-87. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestTiledMap {
            get {
                return ResourceManager.GetString("TestTiledMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///WMS configuration document for
        ///
        ///http://nowcoast.noaa.gov/wms/com.esri.wms.Esrimap/obs
        /// --&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///  &lt;gml:DerivedCRS gml:id=&quot;EPSG:4326&quot;&gt;
        ///    &lt;gml:metaDataProperty&gt;
        ///      &lt;gml:GenericMet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wms_config_example1 {
            get {
                return ResourceManager.GetString("wms_config_example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///WMS configuration document for
        ///
        ///http://trac.osgeo.org/mapguide/ticket/1680
        /// --&gt;
        ///&lt;fdo:DataStore xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns:gml=&quot;http://www.opengis.net/gml&quot; xmlns:fdo=&quot;http://fdo.osgeo.org/schemas&quot; xmlns:fds=&quot;http://fdo.osgeo.org/schemas/fds&quot;&gt;
        ///    &lt;gml:DerivedCRS id=&quot;EPSG:21781&quot;&gt;
        ///        &lt;gml:metaDataProperty&gt;
        ///            &lt;gml:GenericMetaD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wms_config_example2 {
            get {
                return ResourceManager.GetString("wms_config_example2", resourceCulture);
            }
        }
    }
}
