//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MgCooker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MgCooker.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I heard you the first time!
        ///Please be patient..
        /// </summary>
        internal static string AlreadyAborting {
            get {
                return ResourceManager.GetString("AlreadyAborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect: {0}.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Group: \t{0} ({1} of {2}).
        /// </summary>
        internal static string ConsoleCurrentGroup {
            get {
                return ResourceManager.GetString("ConsoleCurrentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Map:   \t{0} ({1} of {2}).
        /// </summary>
        internal static string ConsoleCurrentMap {
            get {
                return ResourceManager.GetString("ConsoleCurrentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Scale: \t1:{0} ({1} of {2}).
        /// </summary>
        internal static string ConsoleCurrentScale {
            get {
                return ResourceManager.GetString("ConsoleCurrentScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Tile:  \t{0} of {1}.
        /// </summary>
        internal static string ConsoleCurrentTile {
            get {
                return ResourceManager.GetString("ConsoleCurrentTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error count: {0}, last exception: {1}.
        /// </summary>
        internal static string ConsoleErrorSummary {
            get {
                return ResourceManager.GetString("ConsoleErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group estimate:  \t{0}.
        /// </summary>
        internal static string ConsoleGroupDuration {
            get {
                return ResourceManager.GetString("ConsoleGroupDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group duration:  \t{0}.
        /// </summary>
        internal static string ConsoleGroupEstimate {
            get {
                return ResourceManager.GetString("ConsoleGroupEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rendering group {1} ({2} of {3}).
        /// </summary>
        internal static string ConsoleOperationBeginGroup {
            get {
                return ResourceManager.GetString("ConsoleOperationBeginGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rendering map {1}.
        /// </summary>
        internal static string ConsoleOperationBeginMap {
            get {
                return ResourceManager.GetString("ConsoleOperationBeginMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rendering scale 1:{1} ({2} of {3}).
        /// </summary>
        internal static string ConsoleOperationBeginScale {
            get {
                return ResourceManager.GetString("ConsoleOperationBeginScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rendered group {1} in {2}.
        /// </summary>
        internal static string ConsoleOperationFinishGroup {
            get {
                return ResourceManager.GetString("ConsoleOperationFinishGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rendered map {1} in {2}.
        /// </summary>
        internal static string ConsoleOperationFinishMap {
            get {
                return ResourceManager.GetString("ConsoleOperationFinishMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Rendered scale 1:{1} in {2}.
        /// </summary>
        internal static string ConsoleOperationFinishScale {
            get {
                return ResourceManager.GetString("ConsoleOperationFinishScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed {0} of {1} tiles in {2}, expected duration: {3}.
        /// </summary>
        internal static string ConsoleOperationFinishTile {
            get {
                return ResourceManager.GetString("ConsoleOperationFinishTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update time:   \t{0}.
        /// </summary>
        internal static string ConsoleUpdateTime {
            get {
                return ResourceManager.GetString("ConsoleUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1}.
        /// </summary>
        internal static string CurrentGroupStatus {
            get {
                return ResourceManager.GetString("CurrentGroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile {0:###,###,###,###} of {1:###,###,###,###} {2}.
        /// </summary>
        internal static string CurrentTileCounter {
            get {
                return ResourceManager.GetString("CurrentTileCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files ({0}).
        /// </summary>
        internal static string FileTypeAllFiles {
            get {
                return ResourceManager.GetString("FileTypeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell Script ({0}).
        /// </summary>
        internal static string FileTypeShellScript {
            get {
                return ResourceManager.GetString("FileTypeShellScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Inaccurate measure of remaining time &gt;.
        /// </summary>
        internal static string InsufficientTimePassed {
            get {
                return ResourceManager.GetString("InsufficientTimePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal error occured: {0}.
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} was not found, unable to use the Native connection method.
        ///Either copy in the file, or do not use the Native connection method.
        /// </summary>
        internal static string MissingWebConfigFile {
            get {
                return ResourceManager.GetString("MissingWebConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MgCooker is now paused, click OK to resume rendering.
        /// </summary>
        internal static string PauseMessage {
            get {
                return ResourceManager.GetString("PauseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, remaining time: {1}.
        /// </summary>
        internal static string RemainingTime {
            get {
                return ResourceManager.GetString("RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} failed tiles).
        /// </summary>
        internal static string TileErrorCount {
            get {
                return ResourceManager.GetString("TileErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Generation Complete. The operation completed in {0}h {1}m {2}s.
        /// </summary>
        internal static string TileGenerationCompleted {
            get {
                return ResourceManager.GetString("TileGenerationCompleted", resourceCulture);
            }
        }
    }
}
