//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.FDO.Expressions {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.FDO.Expressions.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Parsing Expression: {0}{1}.
        /// </summary>
        internal static string ExpressionParseError {
            get {
                return ResourceManager.GetString("ExpressionParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Parsing Filter: {0}{1}.
        /// </summary>
        internal static string FilterParseError {
            get {
                return ResourceManager.GetString("FilterParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valueis not a valid FDO date string: {0}.
        /// </summary>
        internal static string InvalidFdoDateString {
            get {
                return ResourceManager.GetString("InvalidFdoDateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid FDO timestamp string: {0}.
        /// </summary>
        internal static string InvalidFdoTimestampString {
            get {
                return ResourceManager.GetString("InvalidFdoTimestampString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a valid FDO time string: {0}.
        /// </summary>
        internal static string InvalidFdoTimeString {
            get {
                return ResourceManager.GetString("InvalidFdoTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parser Error.
        /// </summary>
        internal static string ParserErrorMessage {
            get {
                return ResourceManager.GetString("ParserErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown keyword: {0}.
        /// </summary>
        internal static string UnknownKeyword {
            get {
                return ResourceManager.GetString("UnknownKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operator: {0}.
        /// </summary>
        internal static string UnknownOperator {
            get {
                return ResourceManager.GetString("UnknownOperator", resourceCulture);
            }
        }
    }
}
