//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maestro.AddIn.Rest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maestro.AddIn.Rest.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration deleted.
        /// </summary>
        internal static string ConfigurationDeleted {
            get {
                return ResourceManager.GetString("ConfigurationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration saved.
        /// </summary>
        internal static string ConfigurationSaved {
            get {
                return ResourceManager.GetString("ConfigurationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete configuration.
        /// </summary>
        internal static string DeleteConfiguration {
            get {
                return ResourceManager.GetString("DeleteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving configuration: {0}.
        /// </summary>
        internal static string ErrorSavingConfiguration {
            get {
                return ResourceManager.GetString("ErrorSavingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDO Class.
        /// </summary>
        internal static string FdoClass {
            get {
                return ResourceManager.GetString("FdoClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration has a missing or invalid source configuration.
        /// </summary>
        internal static string InvalidSourceConfiguration {
            get {
                return ResourceManager.GetString("InvalidSourceConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source specified. Please specify a source from a Feature Source or Layer Definition first.
        /// </summary>
        internal static string NoSourceInConfiguration {
            get {
                return ResourceManager.GetString("NoSourceInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a vector layer: {0}.
        /// </summary>
        internal static string NotAVectorLayer {
            get {
                return ResourceManager.GetString("NotAVectorLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this configuration?.
        /// </summary>
        internal static string PromptDeleteConfiguration {
            get {
                return ResourceManager.GetString("PromptDeleteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST Explorer.
        /// </summary>
        internal static string RestExplorer {
            get {
                return ResourceManager.GetString("RestExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select class name.
        /// </summary>
        internal static string SelectClassName {
            get {
                return ResourceManager.GetString("SelectClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the URI part for this configuration. If the URI part already exists, saving will overwrite the existing configuration.
        /// </summary>
        internal static string UriPartRequrired {
            get {
                return ResourceManager.GetString("UriPartRequrired", resourceCulture);
            }
        }
    }
}
