//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.MapGuide.Maestro.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LengthyOperation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LengthyOperation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.MapGuide.Maestro.Strings.LengthyOperation", typeof(LengthyOperation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main part of the operation has already been performed.
        ///If you cancel the remainder of this operation, some references may not be updated properly.
        ///Do you want to cancel the remainder of the operation?.
        /// </summary>
        internal static string CancelNotRecomendedConfirmation {
            get {
                return ResourceManager.GetString("CancelNotRecomendedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying the selected folder requires the following items to be copied..
        /// </summary>
        internal static string CopyFolderCopyConfirmation {
            get {
                return ResourceManager.GetString("CopyFolderCopyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying the selected folder requires that the following resources are updated.
        /// </summary>
        internal static string CopyFolderUpdateConfirmation {
            get {
                return ResourceManager.GetString("CopyFolderUpdateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured: {0}.
        ///Do you want to retry the operation?.
        /// </summary>
        internal static string ErrorOccuredRetryQuestion {
            get {
                return ResourceManager.GetString("ErrorOccuredRetryQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested method was not found in the API. Most likely, the API has been updated, and the function names changed.
        /// </summary>
        internal static string MissingMethodInternalError {
            get {
                return ResourceManager.GetString("MissingMethodInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A move or rename of the selected folder requires the following items to be updated..
        /// </summary>
        internal static string MoveFolderConfirmation {
            get {
                return ResourceManager.GetString("MoveFolderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A move or rename of the selected resource requires the following items to be updated..
        /// </summary>
        internal static string MoveResourceConfirmation {
            get {
                return ResourceManager.GetString("MoveResourceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please call the &quot;InitializeDialog&quot; method before displaying the dialog.
        /// </summary>
        internal static string NotInitializedInternalError {
            get {
                return ResourceManager.GetString("NotInitializedInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while performing the operation: {0}.
        /// </summary>
        internal static string OperationFailedError {
            get {
                return ResourceManager.GetString("OperationFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the list of files to be processed.
        /// </summary>
        internal static string OtherOperationConfirmation {
            get {
                return ResourceManager.GetString("OtherOperationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation: {0}.
        /// </summary>
        internal static string UnknownOperationInternalError {
            get {
                return ResourceManager.GetString("UnknownOperationInternalError", resourceCulture);
            }
        }
    }
}
