//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.MapGuide.Maestro.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceProperties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceProperties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.MapGuide.Maestro.Strings.ResourceProperties", typeof(ResourceProperties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to decode the current bounds,
        ///you must re-enter the epsg code in the SRS tag manually.
        ///Error message: {0}..
        /// </summary>
        internal static string BoundsDecodeError {
            get {
                return ResourceManager.GetString("BoundsDecodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must manually enter the EPSG code for the generated bounds..
        /// </summary>
        internal static string EpsgMissingWarning {
            get {
                return ResourceManager.GetString("EpsgMissingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherited.
        /// </summary>
        internal static string InheritedAccess {
            get {
                return ResourceManager.GetString("InheritedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing bounds tag.
        /// </summary>
        internal static string MissingBoundsError {
            get {
                return ResourceManager.GetString("MissingBoundsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access.
        /// </summary>
        internal static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spatial data found in FeatureSource.
        /// </summary>
        internal static string NoSpatialDataError {
            get {
                return ResourceManager.GetString("NoSpatialDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spatial data found in FeatureSource, one or more queries failed to execute.
        /// </summary>
        internal static string NoSpatialDataWithFailuresError {
            get {
                return ResourceManager.GetString("NoSpatialDataWithFailuresError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read only.
        /// </summary>
        internal static string ReadOnlyAccess {
            get {
                return ResourceManager.GetString("ReadOnlyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read/write.
        /// </summary>
        internal static string ReadWriteAccess {
            get {
                return ResourceManager.GetString("ReadWriteAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read resource references.
        /// </summary>
        internal static string ReferenceReadError {
            get {
                return ResourceManager.GetString("ReferenceReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read resource references: {0}.
        /// </summary>
        internal static string ReferenceReadSpecificError {
            get {
                return ResourceManager.GetString("ReferenceReadSpecificError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the resource properties: {0}.
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain the extent for the WFS data.
        ///Error message: {0}.
        /// </summary>
        internal static string WFSBoundsReadError {
            get {
                return ResourceManager.GetString("WFSBoundsReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to obtain the extent for the WMS data.
        ///Error message: {0}.
        /// </summary>
        internal static string WMSBoundsReadError {
            get {
                return ResourceManager.GetString("WMSBoundsReadError", resourceCulture);
            }
        }
    }
}
