#region Disclaimer / License

// Copyright (C) 2014, Jackie Ng
// https://github.com/jumpinjackie/mapguide-maestro
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
//

#endregion Disclaimer / License
using System;
using Xunit;

namespace OSGeo.MapGuide.MaestroAPI.Schema.Tests
{
    public class SchemaTests
    {
        [Fact]
        public void ClassDefinitionTest()
        {
            Assert.Throws<ArgumentNullException>(() => new ClassDefinition(null, ""));
            Assert.Throws<ArgumentException>(() => new ClassDefinition("", ""));

            var cls = new ClassDefinition("Foo", "Bar");
            Assert.Equal("Foo", cls.Name);
            Assert.Equal("Bar", cls.Description);
            Assert.Empty(cls.IdentityProperties);
            Assert.Empty(cls.Properties);
            Assert.Null(cls.Parent);
        }

        [Fact]
        public void GetOrdinalTest()
        {
            var cls = new ClassDefinition("Foo", "Bar");
            Assert.True(cls.GetOrdinal("Prop1") < 0);

            var prop = new DataPropertyDefinition("Prop1", "");
            prop.DataType = DataPropertyType.String;
            cls.AddProperty(prop);
            Assert.True(cls.GetOrdinal("Prop1") >= 0);
        }

        [Fact]
        public void ClearIdentityPropertiesTest()
        {
            var cls = new ClassDefinition("Foo", "Bar");
            var prop = new DataPropertyDefinition("ID", "");
            prop.DataType = DataPropertyType.Int32;
            prop.IsAutoGenerated = true;
            cls.AddProperty(prop, true);
            Assert.Equal(cls, prop.Parent);
            Assert.Single(cls.Properties);
            Assert.Single(cls.IdentityProperties);
            Assert.True(cls.GetOrdinal("ID") >= 0);
            cls.ClearIdentityProperties();
            Assert.Empty(cls.IdentityProperties);
        }

        [Fact]
        public void IndexOfPropertyTest()
        {
            var cls = new ClassDefinition("Foo", "Bar");
            var prop = new DataPropertyDefinition("ID", "");
            prop.DataType = DataPropertyType.Int32;
            prop.IsAutoGenerated = true;
            cls.AddProperty(prop, true);
            Assert.Equal(cls, prop.Parent);
            Assert.Single(cls.Properties);
            Assert.Single(cls.IdentityProperties);
            Assert.True(cls.GetOrdinal("ID") >= 0);

            var prop2 = new DataPropertyDefinition("Prop1", "");
            Assert.True(cls.IndexOfProperty(prop2) < 0);
            Assert.True(cls.IndexOfProperty(prop) >= 0);
        }

        [Fact]
        public void RemovePropertyTest()
        {
            var cls = new ClassDefinition("Foo", "Bar");
            var prop = new DataPropertyDefinition("ID", "");
            prop.DataType = DataPropertyType.Int32;
            prop.IsAutoGenerated = true;
            var prop2 = new DataPropertyDefinition("Prop1", "");
            cls.AddProperty(prop, true);
            cls.AddProperty(prop2);
            Assert.Equal(cls, prop.Parent);
            Assert.Equal(cls, prop2.Parent);
            Assert.Equal(2, cls.Properties.Count);
            Assert.Single(cls.IdentityProperties);

            cls.RemoveProperty("Prop1");
            Assert.Single(cls.Properties);
            Assert.Single(cls.IdentityProperties);
            Assert.True(cls.IndexOfProperty(prop2) < 0);

            cls.RemoveProperty(prop);
            Assert.Empty(cls.Properties);
            Assert.Empty(cls.IdentityProperties);
            Assert.True(cls.IndexOfProperty(prop) < 0);
        }

        [Fact]
        public void RemovePropertyAtTest()
        {
            var cls = new ClassDefinition("Foo", "Bar");
            var prop = new DataPropertyDefinition("ID", "");
            prop.DataType = DataPropertyType.Int32;
            prop.IsAutoGenerated = true;
            var prop2 = new DataPropertyDefinition("Prop1", "");
            cls.AddProperty(prop, true);
            cls.AddProperty(prop2);
            Assert.Equal(cls, prop.Parent);
            Assert.Equal(cls, prop2.Parent);
            Assert.Equal(2, cls.Properties.Count);
            Assert.Single(cls.IdentityProperties);

            int idx1 = cls.GetOrdinal("Prop1");
            Assert.True(idx1 >= 0);
            cls.RemovePropertyAt(idx1);
            Assert.Single(cls.Properties);
            Assert.Single(cls.IdentityProperties);
            Assert.True(cls.IndexOfProperty(prop2) < 0);

            int idx2 = cls.GetOrdinal("ID");
            Assert.True(idx2 >= 0);
            cls.RemovePropertyAt(idx2);
            Assert.Empty(cls.Properties);
            Assert.Empty(cls.IdentityProperties);
            Assert.True(cls.IndexOfProperty(prop) < 0);
        }

        [Fact]
        public void FindPropertyTest()
        {
            var cls = new ClassDefinition("Foo", "Bar");
            var prop = new DataPropertyDefinition("ID", "");
            prop.DataType = DataPropertyType.Int32;
            prop.IsAutoGenerated = true;
            var prop2 = new DataPropertyDefinition("Prop1", "");
            Assert.Null(cls.FindProperty("ID"));
            cls.AddProperty(prop, true);
            Assert.Null(cls.FindProperty("Prop1"));
            cls.AddProperty(prop2);
            Assert.Equal(cls, prop.Parent);
            Assert.Equal(cls, prop2.Parent);
            Assert.Equal(2, cls.Properties.Count);
            Assert.Single(cls.IdentityProperties);

            Assert.NotNull(cls.FindProperty("ID"));
            Assert.NotNull(cls.FindProperty("Prop1"));
        }

        [Fact]
        public void CloneTest()
        {
            var cls = new ClassDefinition("Foo", "Bar");
            var prop = new DataPropertyDefinition("ID", "");
            prop.DataType = DataPropertyType.Int32;
            prop.IsAutoGenerated = true;
            var prop2 = new DataPropertyDefinition("Prop1", "");
            Assert.Null(cls.FindProperty("ID"));
            cls.AddProperty(prop, true);
            Assert.Null(cls.FindProperty("Prop1"));
            cls.AddProperty(prop2);
            Assert.Equal(cls, prop.Parent);
            Assert.Equal(cls, prop2.Parent);
            Assert.Equal(2, cls.Properties.Count);
            Assert.Single(cls.IdentityProperties);

            var cls2 = ClassDefinition.Clone(cls);
            Assert.Equal(cls.Name, cls2.Name);
            Assert.Equal(cls.Description, cls2.Description);
            Assert.Equal(cls.Properties.Count, cls2.Properties.Count);
            Assert.Equal(cls.IdentityProperties.Count, cls2.IdentityProperties.Count);
            Assert.NotEqual(cls, cls2);
        }
    }
}
