//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSGeo.MapGuide.MaestroAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OSGeo.MapGuide.MaestroAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select More.
        /// </summary>
        internal static string ADF_Flyout_SelectMore {
            get {
                return ResourceManager.GetString("ADF_Flyout_SelectMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ADF_Flyout_View {
            get {
                return ResourceManager.GetString("ADF_Flyout_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string ADF_Flyout_Zoom {
            get {
                return ResourceManager.GetString("ADF_Flyout_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map with ID {0} does not point to a valid map.
        /// </summary>
        internal static string ADF_MapInvalidError {
            get {
                return ResourceManager.GetString("ADF_MapInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion application does not specify a map.
        /// </summary>
        internal static string ADF_MapMissingError {
            get {
                return ResourceManager.GetString("ADF_MapMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating MapDefinition {0}, message: {1}.
        /// </summary>
        internal static string ADF_MapValidationError {
            get {
                return ResourceManager.GetString("ADF_MapValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fusion application specifies a start view that is outside the map&apos;s initial extents.
        /// </summary>
        internal static string ADF_ViewOutsideMapExtents {
            get {
                return ResourceManager.GetString("ADF_ViewOutsideMapExtents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create buffers around the selected features.
        /// </summary>
        internal static string ADF_Widget_Buffer_Desc {
            get {
                return ResourceManager.GetString("ADF_Widget_Buffer_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer.
        /// </summary>
        internal static string ADF_Widget_Buffer_Label {
            get {
                return ResourceManager.GetString("ADF_Widget_Buffer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure distances and areas on the map.
        /// </summary>
        internal static string ADF_Widget_Measure_Desc {
            get {
                return ResourceManager.GetString("ADF_Widget_Measure_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        internal static string ADF_Widget_Measure_Label {
            get {
                return ResourceManager.GetString("ADF_Widget_Measure_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next view.
        /// </summary>
        internal static string ADF_Widget_NextView_Desc {
            get {
                return ResourceManager.GetString("ADF_Widget_NextView_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ADF_Widget_NextView_Label {
            get {
                return ResourceManager.GetString("ADF_Widget_NextView_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to previous view.
        /// </summary>
        internal static string ADF_Widget_PreviousView_Desc {
            get {
                return ResourceManager.GetString("ADF_Widget_PreviousView_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string ADF_Widget_PreviousView_Label {
            get {
                return ResourceManager.GetString("ADF_Widget_PreviousView_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in by a preset increment.
        /// </summary>
        internal static string ADF_Widget_ZoomIn_Desc {
            get {
                return ResourceManager.GetString("ADF_Widget_ZoomIn_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        internal static string ADF_Widget_ZoomIn_Label {
            get {
                return ResourceManager.GetString("ADF_Widget_ZoomIn_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out by a preset increment.
        /// </summary>
        internal static string ADF_Widget_ZoomOut_Desc {
            get {
                return ResourceManager.GetString("ADF_Widget_ZoomOut_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        internal static string ADF_Widget_ZoomOut_Label {
            get {
                return ResourceManager.GetString("ADF_Widget_ZoomOut_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ApplicationDefinition xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xsi:noNamespaceSchemaLocation=&quot;ApplicationDefinition-1.0.0.xsd&quot;&gt;
        ///  &lt;TemplateUrl&gt;fusion/templates/mapguide/slate/index.html&lt;/TemplateUrl&gt;
        ///  &lt;MapSet&gt;
        ///    &lt;MapGroup id=&quot;MgMainMapId&quot;&gt;
        ///      &lt;Map&gt;
        ///        &lt;Type&gt;MapGuide&lt;/Type&gt;
        ///        &lt;SingleTile&gt;true&lt;/SingleTile&gt;
        ///        &lt;Extension&gt;
        ///          &lt;ResourceId /&gt;
        ///          &lt;SelectionAsOverlay&gt;true&lt;/SelectionAsOverla [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BaseTemplate_ApplicationDefinition {
            get {
                return ResourceManager.GetString("BaseTemplate_ApplicationDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create load procedure of type: .
        /// </summary>
        internal static string CannotCreateLoadProcedureSubType {
            get {
                return ResourceManager.GetString("CannotCreateLoadProcedureSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied resource: {0}.
        /// </summary>
        internal static string CopiedResource {
            get {
                return ResourceManager.GetString("CopiedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coordinate system specified. The coordinate system if not specified will default to LL84.
        /// </summary>
        internal static string DS_NoCoordinateSpace {
            get {
                return ResourceManager.GetString("DS_NoCoordinateSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No source DWF file specified.
        /// </summary>
        internal static string DS_NoSourceSpecified {
            get {
                return ResourceManager.GetString("DS_NoSourceSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Document: Expected attributes at the root level node.
        /// </summary>
        internal static string ERR_BAD_DOCUMENT_NO_ROOT_ATTRIBUTES {
            get {
                return ResourceManager.GetString("ERR_BAD_DOCUMENT_NO_ROOT_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource cannot be downgraded. It is already older than the version this converter can downgrade to.
        /// </summary>
        internal static string ERR_CANNOT_DOWNGRADE_OLDER_RESOURCE {
            get {
                return ResourceManager.GetString("ERR_CANNOT_DOWNGRADE_OLDER_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource cannot be upgraded. It is already newer than what this converter can upgrade to.
        /// </summary>
        internal static string ERR_CANNOT_UPGRADE_NEWER_RESOURCE {
            get {
                return ResourceManager.GetString("ERR_CANNOT_UPGRADE_NEWER_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource converter for {0} is already registered.
        /// </summary>
        internal static string ERR_CONVERTER_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("ERR_CONVERTER_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature source does not connect an externally aliased file.
        /// </summary>
        internal static string ERR_FS_NO_ALIAS {
            get {
                return ResourceManager.GetString("ERR_FS_NO_ALIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature source does not connect to an embedded data file.
        /// </summary>
        internal static string ERR_FS_NO_EMBEDDED_DATA {
            get {
                return ResourceManager.GetString("ERR_FS_NO_EMBEDDED_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no downgrade path to the desired resource version.
        /// </summary>
        internal static string ERR_NO_DOWNGRADE_PATH {
            get {
                return ResourceManager.GetString("ERR_NO_DOWNGRADE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no registered validator for {0} v{1}. Validation cannot be performed.
        /// </summary>
        internal static string ERR_NO_REGISTERED_VALIDATOR {
            get {
                return ResourceManager.GetString("ERR_NO_REGISTERED_VALIDATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find matching serializer for this resource: .
        /// </summary>
        internal static string ERR_NO_SERIALIZER {
            get {
                return ResourceManager.GetString("ERR_NO_SERIALIZER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no upgrade path to the desired resource version.
        /// </summary>
        internal static string ERR_NO_UPGRADE_PATH {
            get {
                return ResourceManager.GetString("ERR_NO_UPGRADE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection attached to this resource.
        /// </summary>
        internal static string ERR_RESOURCE_NOT_ATTACHED {
            get {
                return ResourceManager.GetString("ERR_RESOURCE_NOT_ATTACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A resource serializer has already been registered for {0} v{1}.
        /// </summary>
        internal static string ERR_SERIALIZER_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("ERR_SERIALIZER_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory method already registered for version: .
        /// </summary>
        internal static string FactoryMethodAlreadyRegistered {
            get {
                return ResourceManager.GetString("FactoryMethodAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test failed.
        /// </summary>
        internal static string FS_ConnectionTestFailed {
            get {
                return ResourceManager.GetString("FS_ConnectionTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spatial context extent appears to be invalid (or default).
        /// </summary>
        internal static string FS_DefaultSpatialContextWarning {
            get {
                return ResourceManager.GetString("FS_DefaultSpatialContextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty spatial context extent detected.
        /// </summary>
        internal static string FS_EmptySpatialContextWarning {
            get {
                return ResourceManager.GetString("FS_EmptySpatialContextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not obtain identity properties for {0}. This class either has no identity properties and/or is derived from a view with no uniquely identifiable columns. Attempting to create feature joins from this class may produce unexpected results..
        /// </summary>
        internal static string FS_NoPrimaryKeyOrView {
            get {
                return ResourceManager.GetString("FS_NoPrimaryKeyOrView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spatial contexts found. If this feature source is strictly used for Feature Joins, this warning can be safely ignored.
        /// </summary>
        internal static string FS_NoSpatialContextWarning {
            get {
                return ResourceManager.GetString("FS_NoSpatialContextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No primary key defined for class: {0}, features will not be selectable and feature joins on this class may produce unexpected results.
        /// </summary>
        internal static string FS_PrimaryKeyMissingInformation {
            get {
                return ResourceManager.GetString("FS_PrimaryKeyMissingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read identity properties: {0}.
        /// </summary>
        internal static string FS_PrimaryKeyReadError {
            get {
                return ResourceManager.GetString("FS_PrimaryKeyReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read schema description: {0}.
        /// </summary>
        internal static string FS_SchemaReadError {
            get {
                return ResourceManager.GetString("FS_SchemaReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schemas found in datasource.
        /// </summary>
        internal static string FS_SchemasMissingWarning {
            get {
                return ResourceManager.GetString("FS_SchemasMissingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read spatial context: {0}.
        /// </summary>
        internal static string FS_SpatialContextReadError {
            get {
                return ResourceManager.GetString("FS_SpatialContextReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load specified Drawing Source.
        /// </summary>
        internal static string LDF_DrawingSourceError {
            get {
                return ResourceManager.GetString("LDF_DrawingSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load specified Feature Source.
        /// </summary>
        internal static string LDF_FeatureSourceLoadError {
            get {
                return ResourceManager.GetString("LDF_FeatureSourceLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find geometry column {0} in schema {1} on featuresource {2}.
        /// </summary>
        internal static string LDF_GeometryMissingError {
            get {
                return ResourceManager.GetString("LDF_GeometryMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer is missing core information.
        /// </summary>
        internal static string LDF_LayerNullError {
            get {
                return ResourceManager.GetString("LDF_LayerNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum scale ({0}) is larger than the maximum scale ({1}).
        /// </summary>
        internal static string LDF_MinAndMaxScaleSwappedError {
            get {
                return ResourceManager.GetString("LDF_MinAndMaxScaleSwappedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No FeatureSource is assigned to the layer.
        /// </summary>
        internal static string LDF_MissingFeatureSourceError {
            get {
                return ResourceManager.GetString("LDF_MissingFeatureSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Geometry is assigned to the layer.
        /// </summary>
        internal static string LDF_MissingGeometryError {
            get {
                return ResourceManager.GetString("LDF_MissingGeometryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scale ranges are defined, no data can be displayed.
        /// </summary>
        internal static string LDF_MissingScaleRangesError {
            get {
                return ResourceManager.GetString("LDF_MissingScaleRangesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one scale ranges is defined, this is valid, but unsupported by Maestro.
        /// </summary>
        internal static string LDF_MultipleScaleRangesWarning {
            get {
                return ResourceManager.GetString("LDF_MultipleScaleRangesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scale range {0}-{1} overlaps the range {2}-{3}.
        /// </summary>
        internal static string LDF_ScaleRangesOverlapInformation {
            get {
                return ResourceManager.GetString("LDF_ScaleRangesOverlapInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate column and schema.
        /// </summary>
        internal static string LDF_SchemaAndColumnReadFailedError {
            get {
                return ResourceManager.GetString("LDF_SchemaAndColumnReadFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find schema {0} in featuresource {1}.
        /// </summary>
        internal static string LDF_SchemaMissingError {
            get {
                return ResourceManager.GetString("LDF_SchemaMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced sheet layer {0} not found in sheet {1} of referenced Drawing Source.
        /// </summary>
        internal static string LDF_SheetLayerNotFound {
            get {
                return ResourceManager.GetString("LDF_SheetLayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced sheet {0} not found in referenced Drawing Source.
        /// </summary>
        internal static string LDF_SheetNotFound {
            get {
                return ResourceManager.GetString("LDF_SheetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layer has no type, or the type is unsupported by Maestro.
        /// </summary>
        internal static string LDF_UnsupportedLayerTypeWarning {
            get {
                return ResourceManager.GetString("LDF_UnsupportedLayerTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory method already registered for load procedure type: .
        /// </summary>
        internal static string LoadProcFactoryMethodAlreadyRegistered {
            get {
                return ResourceManager.GetString("LoadProcFactoryMethodAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to SDF option is not supported by Maestro.
        /// </summary>
        internal static string LPROC_ConvertToSdf3NotSupported {
            get {
                return ResourceManager.GetString("LPROC_ConvertToSdf3NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWF Load Procedures cannot be executed by Maestro.
        /// </summary>
        internal static string LPROC_DWFNotSupported {
            get {
                return ResourceManager.GetString("LPROC_DWFNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DWG Load Procedures cannot be executed by Maestro.
        /// </summary>
        internal static string LPROC_DWGNotSupported {
            get {
                return ResourceManager.GetString("LPROC_DWGNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generalization of source data is not supported by Maestro.
        /// </summary>
        internal static string LPROC_GeneralizationNotSupported {
            get {
                return ResourceManager.GetString("LPROC_GeneralizationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raster Load Procedures cannot be executed by Maestro.
        /// </summary>
        internal static string LPROC_RasterNotSupported {
            get {
                return ResourceManager.GetString("LPROC_RasterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDF 2 Migration options are not supported by Maestro. Ensure your source files are SDF3 files..
        /// </summary>
        internal static string LPROC_Sdf2OptionsNotSupported {
            get {
                return ResourceManager.GetString("LPROC_Sdf2OptionsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file not found: {0}.
        /// </summary>
        internal static string LPROC_SourceFileNotFound {
            get {
                return ResourceManager.GetString("LPROC_SourceFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from {0} is not visible in the map&apos;s start extent.
        /// </summary>
        internal static string MDF_DataOutsideMapWarning {
            get {
                return ResourceManager.GetString("MDF_DataOutsideMapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has a different coordinate system than the map, this will impact performance as the coordinates are transformed while rendering the map. Maestro cannot validate the extent of the data..
        /// </summary>
        internal static string MDF_DataReprojectionWarning {
            get {
                return ResourceManager.GetString("MDF_DataReprojectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0}&apos;s FeatureSource could not be read: {1}.
        /// </summary>
        internal static string MDF_FeatureSourceReadError {
            get {
                return ResourceManager.GetString("MDF_FeatureSourceReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} has the default legend label.
        /// </summary>
        internal static string MDF_GroupHasDefaultLabelInformation {
            get {
                return ResourceManager.GetString("MDF_GroupHasDefaultLabelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} does not have a legend label.
        /// </summary>
        internal static string MDF_GroupMissingLabelInformation {
            get {
                return ResourceManager.GetString("MDF_GroupMissingLabelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0} does not have a legend label.
        /// </summary>
        internal static string MDF_LayerMissingLabelInformation {
            get {
                return ResourceManager.GetString("MDF_LayerMissingLabelInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The layer name {0} is used for both &quot;{1}&quot; and &quot;{2}&quot;.
        /// </summary>
        internal static string MDF_LayerNameDuplicateWarning {
            get {
                return ResourceManager.GetString("MDF_LayerNameDuplicateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0} could not be read: {1}.
        /// </summary>
        internal static string MDF_LayerReadError {
            get {
                return ResourceManager.GetString("MDF_LayerReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0} has no geometry column.
        /// </summary>
        internal static string MDF_MissingLayerGeometryColumnError {
            get {
                return ResourceManager.GetString("MDF_MissingLayerGeometryColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0} has an invalid Schema.
        /// </summary>
        internal static string MDF_MissingLayerSchemaError {
            get {
                return ResourceManager.GetString("MDF_MissingLayerSchemaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has no spatial context (eg. no coordinate system).
        /// </summary>
        internal static string MDF_MissingSpatialContextWarning {
            get {
                return ResourceManager.GetString("MDF_MissingSpatialContextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has more than one spatial context, the following test results may be inacurate.
        /// </summary>
        internal static string MDF_MultipleSpatialContextsInformation {
            get {
                return ResourceManager.GetString("MDF_MultipleSpatialContextsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a raster layer, and in another coordinate system than the map. No data will be displayed by the layer.
        /// </summary>
        internal static string MDF_RasterReprojectionError {
            get {
                return ResourceManager.GetString("MDF_RasterReprojectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be processed for spatial info: {1}.
        /// </summary>
        internal static string MDF_ResourceReadError {
            get {
                return ResourceManager.GetString("MDF_ResourceReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer {0} is a type that is unsupported by Maestro.
        /// </summary>
        internal static string MDF_UnsupportedLayerTypeWarning {
            get {
                return ResourceManager.GetString("MDF_UnsupportedLayerTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved resource: {0}.
        /// </summary>
        internal static string MovedResource {
            get {
                return ResourceManager.GetString("MovedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving resource ....
        /// </summary>
        internal static string MovingResource {
            get {
                return ResourceManager.GetString("MovingResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a folder resource id: {0}.
        /// </summary>
        internal static string NotAFolder {
            get {
                return ResourceManager.GetString("NotAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition failure: .
        /// </summary>
        internal static string PrecondFailure {
            get {
                return ResourceManager.GetString("PrecondFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is empty: .
        /// </summary>
        internal static string PrecondStringEmpty {
            get {
                return ResourceManager.GetString("PrecondStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null: .
        /// </summary>
        internal static string PrecondValueNull {
            get {
                return ResourceManager.GetString("PrecondValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection does not support required service: .
        /// </summary>
        internal static string RequiredServiceNotSupported {
            get {
                return ResourceManager.GetString("RequiredServiceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find template url for template: .
        /// </summary>
        internal static string TemplateUrlNotFound {
            get {
                return ResourceManager.GetString("TemplateUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown layer version: .
        /// </summary>
        internal static string UnknownLayerVersion {
            get {
                return ResourceManager.GetString("UnknownLayerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown web layout version: .
        /// </summary>
        internal static string UnknownWebLayoutVersion {
            get {
                return ResourceManager.GetString("UnknownWebLayoutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Load Procedure Type.
        /// </summary>
        internal static string UnsupportedLoadProcedureType {
            get {
                return ResourceManager.GetString("UnsupportedLoadProcedureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There web layout has more than one command named: {0}.
        /// </summary>
        internal static string WL_DuplicateCommandName {
            get {
                return ResourceManager.GetString("WL_DuplicateCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search command {0} references more than one property named {1}.
        /// </summary>
        internal static string WL_DuplicateSearchResultColumn {
            get {
                return ResourceManager.GetString("WL_DuplicateSearchResultColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating MapDefinition {0}, message: {1}.
        /// </summary>
        internal static string WL_MapValidationError {
            get {
                return ResourceManager.GetString("WL_MapValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout does not specify a map.
        /// </summary>
        internal static string WL_MissingMapError {
            get {
                return ResourceManager.GetString("WL_MissingMapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu contains a reference to a command that doesn&apos;t exist: {0}.
        /// </summary>
        internal static string WL_NonExistentMenuCommandReference {
            get {
                return ResourceManager.GetString("WL_NonExistentMenuCommandReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Pane contains a reference to a command that does not exist: {0}.
        /// </summary>
        internal static string WL_NonExistentTaskPaneCommandReference {
            get {
                return ResourceManager.GetString("WL_NonExistentTaskPaneCommandReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar contains a reference to a command that does not exist: {0}.
        /// </summary>
        internal static string WL_NonExistentToolbarCommandReference {
            get {
                return ResourceManager.GetString("WL_NonExistentToolbarCommandReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout specifies a start view that is outside the map&apos;s initial extents.
        /// </summary>
        internal static string WL_StartViewOutsideExtentsWarning {
            get {
                return ResourceManager.GetString("WL_StartViewOutsideExtentsWarning", resourceCulture);
            }
        }
    }
}
