//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maestro.AddIn.GeoRest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maestro.AddIn.GeoRest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_list {
            get {
                object obj = ResourceManager.GetObject("application-list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_circle_045_left {
            get {
                object obj = ResourceManager.GetObject("arrow-circle-045-left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap disk {
            get {
                object obj = ResourceManager.GetObject("disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_task {
            get {
                object obj = ResourceManager.GetObject("document-task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only files named restcfg.xml can be edited.
        /// </summary>
        internal static string ErrCanOnlyEditRestCfg {
            get {
                return ResourceManager.GetString("ErrCanOnlyEditRestCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified configuration root directory does not exist.
        /// </summary>
        internal static string ErrConfigRootDoesNotExist {
            get {
                return ResourceManager.GetString("ErrConfigRootDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoRest URL not specified.
        /// </summary>
        internal static string ErrGeoRestUrlNotSpecified {
            get {
                return ResourceManager.GetString("ErrGeoRestUrlNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any previewable representations in this file.
        /// </summary>
        internal static string ErrNoPreviewableRepresentations {
            get {
                return ResourceManager.GetString("ErrNoPreviewableRepresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not restcfg.xml. Cannot extract previewable representations.
        /// </summary>
        internal static string ErrPreviewNotRestCfg {
            get {
                return ResourceManager.GetString("ErrPreviewNotRestCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified restcfg.xml is missing the top-level &lt;Resource&gt; node. This is probably an invalid document.
        /// </summary>
        internal static string ErrRestCfgMissingResourceNode {
            get {
                return ResourceManager.GetString("ErrRestCfgMissingResourceNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified restcfg.xml is missing a uripart attribute in its &lt;Resource&gt; element. Previewable representations cannot be determined without this attribute.
        /// </summary>
        internal static string ErrRestCfgMissingUriPart {
            get {
                return ResourceManager.GetString("ErrRestCfgMissingUriPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved to: {0}.
        /// </summary>
        internal static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GeoREST Explorer.
        /// </summary>
        internal static string GeoRestExplorer {
            get {
                return ResourceManager.GetString("GeoRestExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maestro Config Saved to {0}.
        /// </summary>
        internal static string MaestroConfigSaved {
            get {
                return ResourceManager.GetString("MaestroConfigSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifier {
            get {
                object obj = ResourceManager.GetObject("magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plug {
            get {
                object obj = ResourceManager.GetObject("plug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML (Many template) - {0}.
        /// </summary>
        internal static string PreviewTypeHtmlMany {
            get {
                return ResourceManager.GetString("PreviewTypeHtmlMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KML (Many template) - {0}.
        /// </summary>
        internal static string PreviewTypeKmlMany {
            get {
                return ResourceManager.GetString("PreviewTypeKmlMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMZ (Many template) - {0}.
        /// </summary>
        internal static string PreviewTypeKmzMany {
            get {
                return ResourceManager.GetString("PreviewTypeKmzMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OData (Raw) - {0}.
        /// </summary>
        internal static string PreviewTypeODataRaw {
            get {
                return ResourceManager.GetString("PreviewTypeODataRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Representation to Preview.
        /// </summary>
        internal static string PromptSelectPreview {
            get {
                return ResourceManager.GetString("PromptSelectPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Representation Preview.
        /// </summary>
        internal static string TitleSelectPreview {
            get {
                return ResourceManager.GetString("TitleSelectPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Document is well-formed.
        /// </summary>
        internal static string XmlWellFormed {
            get {
                return ResourceManager.GetString("XmlWellFormed", resourceCulture);
            }
        }
    }
}
